### ISSUE TITLE
Get a suitable logo for the Pharo language track

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#12]
We need a logo to represent Pharo on the Exercism web site. There is a quick guide on this [here](https://github.com/exercism/docs/blob/master/language-tracks/launch/landing-page.md#language-track-icon). 

We need the following:
- [x] Permission to use an offical Pharo logo
- [x] Attribution rights of the logo
- [x] A link to an example of the logo

With that in hand the next thing to do is to open up an issue on [exercism/website-icons](https://github.com/exercism/website-icons/issues) with the above information.

**Comment by bencoman** [comment]
Logo media are available at https://files.pharo.org/media/logo/

I'll email  board@pharo.org  requesting use permission and attribution
rights.

In the meantime I've mocked up two options...

**Comment by samWson** [comment]
@bencoman Good work. I personally like option-1 more. Looking at all the exist language icons I think it fits the style of the others better.

**Comment by estebanlm** [comment]
I like option 1 more too :)

**Comment by estebanlm** [comment]
yes, we said "go ahead" :)

**Comment by bencoman** [comment]
Board members listed at https://pharo.org/about.

Below is the quick response I received on email,
but I was hoping for a direct response here also. Thx Esteban.


On 15 July 2018 at 03:51, Stéphane Ducasse <stephane.ducasse@inria.fr>
wrote:
> sure!
>
> Stef
>  Stéphane Ducasse
>
> On 14 Jul 2018, at 10:46, Ben Coman <btc@openinworld.com> wrote:
>
> greetings and salutations,
>
> The Exercism site presents a logo for each language track,
> which you can see scrolling down their home page...
>    https://exercism.io
>
> So on their behalf, I'm requesting permission to use the Pharo logo
> to represent the Exercism Pharo language track,
> modified to conform with Exercism's monochrome theme.
>
> I've mocked up some examples at...
>    https://github.com/exercism/pharo/issues/12
>
> cheers -ben

**Comment by samWson** [comment]
@bencoman thanks for taking on this task. @estebanlm thank you and please pass my thanks onto the rest of the Pharo board too.

**Comment by samWson** [comment]
For the attribution rights is there specific text the Pharo community prefers to use or is it enough for us to add something like _Pharo branding used with the permission of the Pharo board_ in our README?

**Comment by bencoman** [comment]
On 27 July 2018 at 17:36, Samuel <notifications@github.com> wrote:

> For the attribution rights is there specific text the Pharo community
> prefers to use or is it enough for us to add something like *Pharo
> branding used with the permission of the Pharo board* in our README?
>
I believe the board will be fine with that.
cheers -ben

**Comment by macta** [comment]
I’ve asked @iHiD to put our logo in place on slack as we are very close now.

**Comment by macta** [comment]
I will also present our progress at PharoDays this week

**Comment by bencoman** [comment]
On Mon, 1 Apr 2019 at 15:18, Tim Mackinnon <notifications@github.com> wrote:

> I will also present our progress at PharoDays this week
>

Thats really great Tim.
cheers -ben

**Comment by iHiD** [comment]
Done. This can be closed.

**Comment by macta** [comment]
@iHiD do we have to do anything - or will it magically appear in the alpha track we see now (at the moment there is still a blank space)

**Comment by iHiD** [comment]
Ah - it's pointing to missing urls due to the track rename. Will sort :)

**Comment by iHiD** [comment]
Also I spelt turquoise wrong.

**Comment by iHiD** [comment]
Fixed.
