### ISSUE TITLE
Do user testing to establish Pharo7 compatablility

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#120]
Pharo7 is released now and I think it is worth our time targeting it for our development. It should help simplify some of our development environment setup by having features like Tonel by default and using the latest version of Iceberg.

What I want to do is use our exercism tools like a user and see what breaks through the whole process for each OS. It's also worth checking our development environment setup as some steps may now be redundant.

I'm going to get started on some user testing on Windows10 first.

**Comment by samWson** [comment]
Not off to a great start. I'm testing on Windows 10 with Pharo7 64bit and following the install instructions. I ran this bit of code to get things set up:
```smalltalk
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo:master/dev/src';
 load.
```

I get an error right as it's running `Fetching BaselineOfExercism`: `#pathString was sent to nil`. I'm still looking into this as I type. I'll hopefully have more info shortly.

**Comment by samWson** [comment]
As far as I can tell the problem may be that the `LGitRepository` is not initialized (highlighted below). I don't know the inner workings of Metacello so I'm not optimistic in figuring out how to fix this problem.

![error-fetching-baseline](https://user-images.githubusercontent.com/13286932/52464390-6c870480-2bdf-11e9-9781-947d11dac0d8.PNG)

**Comment by macta** [comment]
I will have a go on OS X this morning - however I have noted that 64bit Windows is very beta - so worth repeating with 32bit.

**Comment by macta** [comment]
I get the same problem on OSX - so will investigate whats going on.

**Comment by bencoman** [comment]
The problem is that the "pharo-project/pharo" repository is pre-defined in Pharo 7.  I bumped into similiar problems a few months ago when I found it easier to work on Exercism in Pharo 7.  My work around was to fork exercism/pharo to bencoman/pharo and then go to settings and rename it to bencoman/pharo-exercism.

Try this out...
```
Metacello new 
   baseline: 'Exercism'; 
   repository: 'github://bencoman/pharo-exercism:master/dev/src';
   load.
```
which doesn't complete due to a different error, but at least bypasses the Metacello one.
I think we should consider renaming the exercism/pharo to avoid this being an ongoing issue.

**Comment by macta** [comment]
@bencoman thanks for pointing that out - did you report this to the pharo team back then? It seems a silly limitation of pharo, particularly as this repo is given to us by the exercism team, and I believe its all keyed off the name of the repo matching the language in their "list" (its all very ruby - convention based I think). So I don't think we can easily rename it - and I think its not ideal that we expect people to clone and rename... far too many steps. Saying this - we could plump for pharo-smalltalk as our track name if there isn't an easy fix.

**Comment by macta** [comment]
I've asked on the newsgroup to see if I can get a workaround or better clarity - I guess for now, I'll fork like you and see what else doesn't work.

**Comment by macta** [comment]
I've reported a bug (and have a hacky fix, but it doesn't help us here unless it gets rolled into P7). https://github.com/pharo-project/pharo/issues/2485

**Comment by macta** [comment]
In a zeroconf pharo 7 image - using the above, and a few calypso menu hacks (see #122 ) I was able to fetch hello-world and submit a solution using the new http submission process (nice).

So there is light at the end of the tunnel (not sure about the manifest sub-package that appears - as I found that a bit confusing, but I think we can probably push that info somewhere a bit less obtrusive)

**Comment by macta** [comment]
I've pushed the Calypso menu changes to master (#122) but then realised that without #121 we still have to run in a fork anyway to do testing. So @bencoman is correct - fork the repo, then rename your fork (I used pharo-exercism for now) and then from the command line you can use (replace macta with your user):
```
./pharo-ui Pharo.image eval "
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://macta/pharo-exercism:master/dev/src';
 load.
ExercismManager welcome.
"

On OSX this gets me a calypso browser with Welcome, I can run the tests and follow the Welcome comment instruction to load hello-world - with the nice exercism key prompt and url that lets me easily copy my key (love that).

From Welcome, there is the code critic giving some ugly warnings about TestClasses etc (so need to think about that), and also when I retrieve hello-world - unlike the command line exercism its also bringing down the solution (which is incorrect).

**Comment by samWson** [comment]
Now that the name of our repo is sorted I'll get back to this issue.

**Comment by samWson** [comment]
Started testing again from scratch and got an error. At least it is a new one:
```
LGit_GIT_EEXISTS: Failed to stat file 'C:/Users/sam/Documents/Pharo/images/exercism-test-run-7.0-32...stance/testRaiseUnexpectedMessageWhenTooMuchMessages.st': The filename or extension is too long.
```

I recall we have had this problem before: filenames too long when running on Windows? I tried to look for another issue where we had this problem for a fix but I haven't been able to find one.

**Comment by macta** [comment]
@samWson weird - what is that test ```testRaiseUnexpectedMessageWhenTooMuchMessages``` I don't even see it in the image? I'm assuming this is when you load - is that from the command line or from the playground? Have you cleared out your iceberg cache if re-using an image?

**Comment by macta** [comment]
@samWson if you are around - jump on Discord and we can see if we can diagnose it

**Comment by macta** [comment]
@roelof reported on Discord that it works in 32bit and the first time it worked on 64bit (loading) however he couldn't submit a solution (got a 404) but was able to retrieve an exercise. 32 bit seemed fine.

**Comment by bencoman** [comment]
`testRaiseUnexpectedMessageWhenTooMuchMessages.st` looks like a method name, which indicates FileTree format is being used rather than Tonel (and these "failed to stat file" errors on Windows is precisely one of the reasons for the move to Tonel).  It may be from one of the dependencies that are pulled in.  To identify which, search for that file under `pharo-local/iceberg` directory.

**Comment by samWson** [comment]
I've tested on Windows 10 32bit and everything seems fine. I installed, downloaded an exercise, changed something, submitted the exercise, and saw the result on Exercism.

I'll try another one on Windows with 64bit. Have either of you done a MacOS or Linux test yet? If not I'll get on to those in due course.

**Comment by bencoman** [comment]
On Wed, 27 Feb 2019 at 15:12, Samuel <notifications@github.com> wrote:

> Have either of you done a MacOS or Linux test yet? If not I'll get on to
> those in due course.
>
Nope. I only have Windows at the moment.
cheers -ben

**Comment by samWson** [comment]
I've done a test on Windows 64bit with a Pharo 64bit image with no problems.

I'll try to get another test for MacOS or Linux done this weekend.

**Comment by macta** [comment]
I’ve done mac with 64bit and yes fine

**Comment by macta** [comment]
I think @jaccarmac was using linux so it might be tested. Maybe he can comment (not sure if he can see this or not)

**Comment by jaccarmac** [comment]
I used the latest images from Zeroconf when going through the existing beta issues. It ended up being a little unstable but that instability seemed to be due to alpha Pharo things, not this repo.

Worth noting re: the conflict in Iceberg. This repository was renamed `pharo-smalltalk` at some point, so there's no conflict if you clone `git://exercism/pharo-smalltalk` instead. That was one issue with the README I worked around but never filed a ticket for.

Anyway, overall, my experience on Linux has been pretty good, though I didn't use the scripts from the README as written and I'm technically using a Pharo 8 VM, not Pharo 7.

**Comment by samWson** [comment]
Glad it worked out for you @jaccarmac. Unfortunately when I tested it on my computer it didn't work. I'm running Fedora 29 64bit with a Pharo7 64 bit image and VM. I think the problem is not our repository but rather my particular Linux installation. 
The error is `External module not found` and I think it has something to do with the `LGitLibrary` package when `initializeLibGit2 is called.

I think this issue is sort of solved in that we have proven that our language track works with Pharo 7 across the major OSes. There might be some problems with the various Linux distros not having the right libraries already installed.

I'm thinking we close this issue now, and open up a more specific one if we want to deal with distro specific bugs like my one.

**Comment by samWson** [comment]
Our original purpose for this issue is done for now. Closing.

**Comment by Raincode** [comment]
Hello,

I'm not really sure if this is the right place or the right time, I'm sorry.

I'm running Fedora 31 and downloaded Pharo launcher and had errors on start-up. The headline was "External module not found" and lgit2_init etc. was mentioned, too.

After running the following command, the error did not appear anymore:

`sudo dnf install libgit2-devel`

Maybe this helps someone in the future :)

**Comment by samWson** [comment]
Hi @Raincode. Thanks for the info. I appreciate it and it could very well be useful.
