### ISSUE TITLE
Finish renaming pharo track to pharo-smalltalk

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#121]
For bootstrapping issues internal to pharo, we may have hit a temporary (but longer than several months) issue where our version control tools can't handle a repository called xxx/pharo.

Rather than messing around with more code workarounds, and in the interest of moving this project forward (we got so close and then stalled) - I would like to propose that we rename our exercism project to: pharo-smalltalk

There is a similar example in common-lisp, so its not completely unheard of (and it does allow any other smalltalk variants to follow suite - like amber-smalltalk, the javascript based variant).

I don't know how much trouble this causes inside exercism infrastructure - so we need to find out, but wanted to raise this to assess.

**Comment by samWson** [comment]
I'm all for this. @kytrinyx can you tell us what the impact of renaming our track name will be? Will we need to raise issues elsewhere to get this change made external to this repository?

**Comment by macta** [comment]
Yes it's annoying and frustrating, but if @kytrinyx can confirm that its not too bad (from a github point of view it seems trivial), and hopefully everything is auto-generated and this is a private track?

I think it would unblock us and we can get this out and live so Exercism has some examples of different kinds of environments

**Comment by bencoman** [comment]
I think this is the pragmatic path forward.

**Comment by samWson** [comment]
In order to get a bit more visibility and get this issue resolved faster I've raised an issue [here](https://github.com/exercism/exercism/issues/4710).

**Comment by samWson** [comment]
I got some advice from @iHiD 

>    1. On the website side, it's really simple. I can do it for you on-demand.
>    2. On GitHub, we just need to rename the repos and update and copy anywhere
>    3. The tricky bit is what happens to people's local solutions - their existing solutions are fine (as they're encoded by their ids) but they'll end up with two directories in their filesystem, one for `pharo` and one for `pharo-smalltalk`. I can't see a way around that, and I don't think it hugely matters, but that's the only real thing that I think will break.

> I would suggesting doing (2) then pinging me to do (3) when you're done.

@macta and @bencoman are we ready to rename the repository now? If so I'll get on to this.

**Comment by macta** [comment]
I would like to resolve some pull requests first - give me a day as I don’t know how Pharo will react. I don’t thibk 3 is an issue.

**Comment by bencoman** [comment]
On Sun, 17 Feb 2019 at 11:23, Samuel <notifications@github.com> wrote:
>
> I got some advice from @iHiD
>
> 1. On the website side, it's really simple. I can do it for you on-demand.

Is it a constraint that the website must change to match the github repo?

>
> 2. On GitHub, we just need to rename the repos and update and copy
anywhere

cool.

>
> 3. The tricky bit is what happens to people's local solutions - their
existing solutions are fine (as they're encoded by their ids) but they'll
end up with two directories in their filesystem, one for pharo and one for
pharo-smalltalk.

The filesystem is not used by students.

cheers -ben

>
> I can't see a way around that, and I don't think it hugely matters, but
that's the only real thing that I think will break.
>
> I would suggesting doing (2) then pinging me to do (3) when you're done.
>
> @macta and @bencoman are we ready to rename the repository now? If so
I'll get on to this.

**Comment by macta** [comment]
@samWson go ahead with sorting out the rename, I've cleanly merged my code changes and tested the current master which now works quite well (apart from having to fork the repo and use that fork in the command line instructions).

**Comment by samWson** [comment]
Slight problem here. I can't access the repository settings so I can't change the name. Right at the top of the Github page next to `Insights` should be a `Settings` tab. Both of you please have a look and see if you can change the settings.
I suspect it is a permissions thing and looking in our teams page I don't see a way to change it. I'm going to ask around on the exercism repo again to get this sorted.
@kytrinyx if you can help with this please do.

**Comment by bencoman** [comment]
no `Settings` for me

**Comment by macta** [comment]
No - I don’t have that access either

**Comment by kytrinyx** [comment]
The way we've set it up only organization admins in the Exercism org have access to settings for the various repos. Updating this now.

**Comment by macta** [comment]
Fantastic - the repo, has adopted the new name and we can load the code again with forking (it looks like the track name preserves itself as Pharo - which is great if thats intended). I'll update the readme so we can resume end user testing.

**Comment by kytrinyx** [comment]
I think that our backend code for the website handles GitHub's redirect, so that should "just work". :)

**Comment by macta** [comment]
@kytrinyx if I check in an updated INSTALLATION.md shouldn't it just get re-generated? (sorry its been a while) - becuase it doesn't seem to have picked up the change and regenerated (making me think there is some additional config needed for a checkin webhook or something)?

**Comment by kytrinyx** [comment]
It definitely should pick up changes in the files in `docs/`, in which case maybe it doesn't 'just work'. Dangit :) Ok, that's for me and Jeremy to figure out, then.

**Comment by macta** [comment]
@kytrinyx @iHiD - any chance we can get this fixed, its difficult for us to get Pharo community help when the instructions published on the site are wrong. I'm also loathe to fix the CI running our tests on travis when its not working properly.

**Comment by kytrinyx** [comment]
I *think* Jeremy said he'd do it today.

_Note: I am on a loaner computer, after my laptop had a pretty severe crash (so bad Apple decided to not give it back to me and use it for research, apparently). Anyway, long story short, I don't have access to our production servers at the moment to get this done._

**Comment by iHiD** [comment]
This is done now.

**Comment by iHiD** [comment]
@macta has confirmed this is working so I think this can now be closed.
