### ISSUE TITLE
64 bit windows installation is flakey - gives Git Errors 

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#140]
Started testing again from scratch and got an error on 64bit windows:
```
LGit_GIT_EEXISTS: Failed to stat file 'C:/Users/sam/Documents/Pharo/images/exercism-test-run-7.0-32...stance/testRaiseUnexpectedMessageWhenTooMuchMessages.st': The filename or extension is too long.
```

I recall we have had this problem before: filenames too long when running on Windows? I tried to look for another issue where we had this problem for a fix but I haven't been able to find one.

_Originally posted by @samWson in https://github.com/exercism/pharo-smalltalk/issues/120#issuecomment-465902340_

On Discord/exercism-dev @roelof reports a similar kind of problem on Wndows 10:

He Was able to install Exercism via the playground the first time on 64bit windows - but then wasn't able to submit his hello-world exercise (he got a 404 error) - see separate issue.

He then tried on 32bit windows and it was fine.

When he tried installing 64bit a second time he got the long filename error with filename:
```ruleRBUtlitiesMethodsRuleV1FalsePositve.st```

**Comment by RoelofWobben** [comment]
here a screenshot of the problem 

![afbeelding](https://user-images.githubusercontent.com/47429430/53168084-2025c680-35da-11e9-8f79-19a1fe5e54a2.png)

**Comment by macta** [comment]
We've now identified this is also an issue with 32bit as well (which makes more sense).

The workaround is to use the shared repository setting in Iceberg, and set it to a short path like c:\repo

This still raises the question why it fails on files that aren't even in our project.

**Comment by macta** [comment]
@samWson It would be handy to get the full path of the error file you get above (e.g. testRaiseUnexpectedMessageWhenTooMuchMessages.st) - as I think there might be a deeper iceberg bug going on.

Can you do it and get a longer path to see if it is in one of our pre-reqs?

**Comment by samWson** [comment]
@macta Here is the error message:
```
'C:/Users/sam/Documents/Pharo/images/exercism-test-run-7.0-32bit/pharo-local/iceberg/dionisiydk/StateSpecs/StateSpecs-DSL-PragmaBasedShouldExpressions-Tests.package/SpecOfShouldExpressionDriverTests.class/instance/testRaiseUnexpectedMessageWhenTooMuchMessages.st': The filename or extension is too long.
```

and here is the file path it refers to:
```
C:\Users\sam\Documents\Pharo\images\exercism-test-run-7.0-32bit\pharo-local\iceberg\dionisiydk
```

I got the path above by navigating there manually with Windows explorer. Once I got to that last folder it was empty. No hidden files either.

> Can you do it and get a longer path to see if it is in one of our pre-reqs?

I don't quite understand exactly what your asking here. Let me know if you need more than the above info.

I'm using Pharo launcher so I also had the idea of trying to use just a standalone installation of Pharo or use some other method just to get this file path sorter and see if that would work around the problem.

**Comment by macta** [comment]
@samWson now you have the untruncated error message I can confirm that this is a prerequisite package (not one that we actually want, but we get it via PharoWebBrowser and the tests for one of its sub-packages).

Someone on the mailing list identified what happens - the whole project (as in packages in the project) gets loaded onto disk, and then the Baseline identifies which of those packages get loaded into the image based on group. There are some long test names in the Pragma based tests, but the baseline doesn't seem to load those into the image (and hence why we don't see them in the image).

@RoelofWobben identified a workaround on Discord - if you enable the shared library option in Iceberg, you can enter a path that isn't necesarily where your image and pharo launcher is (so you can pick something really short like: c:\repo). This is the quick fix.

The longer fix is to sort out dependent projects so that they use Tonel and also have a grouping where you can load them without "runtime" dependencies (e.g. we don't need all those tests just for opening a web browser).

**Comment by macta** [comment]
@samWson can I also confirm that the Visit Track menu option actually does open a web browser for you on Windows (if it doesn't even work, then we should just ditch the dependency).

**Comment by macta** [comment]
alpha user hasn't had any problems with this over last few days
