### ISSUE TITLE
Add a reverse test to stop users simply using #reverse

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#142]
This is actually a generic issue, but a good concrete example is to detect in the Reverse exercise if a user has used the selector #reverse and so hasn't learned as much. We could apply this to other exercises as well (maybe generically provide a list of selectors that shouldn't be used)

**Comment by cdlm** [comment]
`#reversed` should raise a flag as well; I'd like to do the PR but first I need to check how you handle development of the track vs doing the exercises…
