### ISSUE TITLE
We are using /v1/solutions api path - is this correct?

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#187]
I noticed that the http request we make to the api, use /v1/solutions  - I've heard people mention that exercism is now v2 - should we be using a v2 path?

Need to check with @kytrinyx if there is a new path or if this one is ok (and for how long) - might be better to update if this is an old one.

**Comment by bencoman** [comment]
Just guessing, but it seemed to me like v2 was abandoned and v3 was a move
back to v1 api.

**Comment by kytrinyx** [comment]
Sorry about the confusion. The API is v1. The _app_ is sometimes referred to as "v2" because it was a complete redesign of the entire user experience.

**Comment by macta** [comment]
@bencoman where did you find these details - presumably in the cli client source? I’d like to put a ref in our code to aid any future development.

**Comment by bencoman** [comment]
Original insights came from sniffing the network with Wireshark.
Then probably also went digging here... https://github.com/exercism/cli/search?q=api&unscoped_q=api

**Comment by macta** [comment]
Closing, as we have the feedback on this
