### ISSUE TITLE
Missing class reference in HelloWorldTest class>>exercise

### ISSUE THREAD

**Issue by Bajger** [exercism/pharo-smalltalk#188]
Problem statement: There is missing reference to ExercismExercise class in method HelloWorldTest class>>exercise
```
HelloWorldTest class>>exercise
	"Answer the configured exercise meta data for this exercise, an ExercismExercise.
	HelloWorld is a special case as it's the first exercise"
	
	^(ExercismExercise for: self) 
		isCore: true;
		isAutoApproved: true;
		difficulty: 1;
		topics: #('introduction' 'strings');
		yourself
```

Steps to reproduce:
- downloaded fresh image Pharo 7 stable 32bit via PharoLauncher
- downloaded exercism via instructions using script
- complete initial exercise and run test
```
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo-smalltalk:master/dev/src';
 load.
 
#ExercismManager asClass welcome.
```

Running on Windows 10 64bit, version of PharoLauncher 1.7.2

**Comment by Bajger** [comment]
Hi Sam. Yes - confirming words from Tim: It was fresh installation (fresh image), I followed steps from Exercism page (from your link). I didn't have any development environment, so I didn't have any repository downloaded prior to installation. @macta Tim, were you able to reproduce it?

**Comment by macta** [comment]
I haven't tried a repo - but I'm sure you are right as its the change I recently made to clean up how we specify meta info for exercises (v.s. overriding lots of methods in ExercismTest, which is rather messy)

**Comment by macta** [comment]
master now fixes this problem
