### ISSUE TITLE
Users can easily see preworked solutions via iceberg

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#198]
It's a little too easy to see the pre-worked solutions as the Exercism package appears in Iceberg.

I thought we might need to create a seperate repo for this - however an Iceberg reset in Welcome will do the trick to stop casual users. (and that's good enough)

**Comment by bencoman** [comment]
I'm in favour of a separate repo for exercises, but I'd need to refresh myself with https://github.com/exercism/pharo-smalltalk/issues/105 to comment.

**Comment by macta** [comment]
I'm not sure we need the extra complication - but we could consider it. Its much easier having it all in one place as you don't have to worry about what layers on what etc.

I think when you actually try editing an exercise you will see what I mean. The latest changes really make it very easy. If we also sort out the generator (as we have discussed), that will also remove a lot of the noise as well.

Anyway - one to explore a bit further down the road I would say. 

For now - I think doing Iceberg reset in the welcome load would by all appearances have the same effect.

**Comment by bencoman** [comment]
Not wanting to completely dismiss #105, but okay for now - I need to work with the existing system more before further judgement,.

**Comment by macta** [comment]
@bencoman - I too will keep an open mind on a separate exercise repo - we may end up moving down that route at some point
