### ISSUE TITLE
Information: Exercism classes grouped by function

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#215]
@macta @bencoman Here is a pair of pictures I drew to help me figure out what all our code does. I didn't have much of a methodology behind this other than just different areas of function for each class. This is just for informational purposes in case it can help someone else.

This was based on the code as it was at c0889bfdf6dd48d8ce58e43a99a1cb9413b9e019 on March 8th 2019.

Hopefully the pictures are good enough to make out. Getting them out of OneNote was far harder than it should have been. In the end I had to resort to screen shots.

![exercism-dev-classes](https://user-images.githubusercontent.com/13286932/54804850-debc3000-4cd9-11e9-9d00-505dd47dd0d1.PNG)

![exercism-tools-classes](https://user-images.githubusercontent.com/13286932/54804854-e4197a80-4cd9-11e9-8545-bec284ad5ad2.PNG)

**Comment by macta** [comment]
I’m not at my computer - but cursory glance looks good - ExcercismExercise is the transient meta-data, and is a kind of Adapter over ExercismTestCase, the latter being an artifact that gets easily stored on Exercism (so those class methods are cheap convenient storage). Seems to work ok for now, and has the advantage of keeping each exercises meta data separate from one another. Of note is that the submissionId (you identified we needed to submit back) is stored as a class instance variable on each testcase - which ExercismExercise retrieves when crested.

**Comment by macta** [comment]
You haven’t covered ExercismSubmission - it’s the data exercism associated with a submitted exercise - I’m still not sure if some of that data belongs in Exercise or not, but so far it hasn’t been needed.

The final piece of interest is ExercismHttpClient - a high level wrapper over znclient that makes for an easier protocol to exercism (it was extracted from the command objects to remove the inheritance chain and make testing easier). It also felt like it cleaned up the code a lot . Equally, was able to move some things to Submission and Exercise too.

It’s not perfect, and I’m sure we could simplify more - but it’s an emergent architecture without being too high brow.

**Comment by macta** [comment]
Last point - the Exception handling burned me a bit yesterday, trying to follow what roelof has done - so cleaned that up too - now the token promoting is done by the httpclient (could dequalky have been the manager), but that felt more consistent with other Pharo exceptions that just trigger and hold any error data.

**Comment by macta** [comment]
@samwson btw, nice job helping document

**Comment by bencoman** [comment]
Nice initiative @samWson.  Definitely useful to anyone wanting to participate in the dev-side of things.
btw, a nice graph editor I've used is... https://www.yworks.com/products/yed

**Comment by samWson** [comment]
Thanks for the compliments team. I only intended this as something to help me understand the project so I could contribute better. If this kind of thing is considered valuable enough I could draw up a proper graph with yEd and store it in our repo. Let me know what you think and I can start a new issue.

**Comment by samWson** [comment]
Closing this off here. Will follow up on more diagrams in a new issue.
