### ISSUE TITLE
Proposal: Lets add ourselves to Awsome Pharo

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#280]
[Awesome Pharo](https://github.com/pharo-open-documentation/awesome-pharo) is a categorized community collection of software, tools, libraries, and frameworks written in Pharo. Like other Awesome XXX repositories it documents what is out there in a language ecosystem.

Adding our language track to Awesome Pharo would be a good way of attracting more people to our project and helping them learn Pharo.

If this idea is agreed to we can open up an issue on Awesome Pharo to get us added.

**Comment by macta** [comment]
I’d vaguely thought of that when it was presented at Pharo Days - thumbs up for me, can you run with it and get us included?

**Comment by samWson** [comment]
Will do. I'll get onto it.

**Comment by macta** [comment]
It’s good having someone on top of this side of things. You should try out some of the exercises too - now we’ve got a decent range - robot and tournament are fun (and it’s interesting comparing how they are approached in Ruby)

**Comment by samWson** [comment]
For info pull request is opened [here](https://github.com/pharo-open-documentation/awesome-pharo/pull/61).

**Comment by samWson** [comment]
Done. We are now listed on Awesome Pharo. Have a look [here](https://github.com/pharo-open-documentation/awesome-pharo#tutorials).

**Comment by macta** [comment]
Nice - thanks for spotting that and following up
