### ISSUE TITLE
Document our use of Exercism REST API

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#281]
This occurred to me as I was thinking about working on #245. The Exercism REST API, which we make use of, isn't documented. We have effectively discovered it ourselves through our work on this repo and properly documenting how we use it would help with future maintenance.

Documentation would also have the side benefit of being useful to the Exercism maintainers and any other language track maintainers who wished to use the API as well.

**Comment by macta** [comment]
good point - reminds me that we should also ask why submitting the same exercise gives a 400 response vs. 304 (not modified)

**Comment by samWson** [comment]
I'm going to get started on this. It is going to take the form of a markdown document for the moment.

**Comment by samWson** [comment]
@bencoman I recall in another issue you managed to get a copy of the [exercism website](https://github.com/exercism/website) working locally on your computer? I've been looking at the website source code to help me write this documentation and I've been trying to run a local server so I can interact with the API. I remember you left some notes on problems you ran into but I can't find them. I'm hoping those notes might help me get the website running on my computer.

**Comment by bencoman** [comment]
[install notes - local copy of Exercism website](https://github.com/exercism/pharo-smalltalk/issues/103)

**Comment by samWson** [comment]
> good point - reminds me that we should also ask why submitting the same exercise gives a 400 response vs. 304 (not modified) - we currently spot 400 and say not modified.

@macta I found the test for that exact condition in the website code. It tests for a `400` response with the message `"No files you submitted have changed since your last iteration"`. So correct behavior according to the tests but not a correct use of status codes according to the [status code definitions](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).

We could submit an issue to change the status code returned to the correct one. Of course that kind of fix would also require our own code to change.
