### ISSUE TITLE
Implement continuous integration

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pharo-smalltalk#3]
Implement a track test suite that can run both locally and on Travis CI. The track test suite should verify that each exercise makes sense, by running the exercise tests against the example solution.

**Definition of terms**

- **exercise test suite**: the test suite that is delivered to Exercism users as part of an Exercism exercise
- **track test suite**: the test suite that helps ensure that all of the exercise test suites in a language track are solvable

**Background**

When implementing an exercise test suite, we want to provide a good user experience for the people writing a solution to the exercise. People should not be confused or overwhelmed.

In most Exercism language tracks, we simulate Test-Driven Development (TDD) by implementing the tests in order of increasing complexity. We try to ensure that each test either

- helps triangulate a solution to be more generic, or
- requires new functionality incrementally.

Many test frameworks will randomize the order of the tests when running them. This is an excellent practice, which helps ensure that subsequent tests are not dependent on side effects from earlier tests. However, in order to simulate TDD we want tests to run *in the order that they are defined*, and we want them to *fail fast*, that is to say, as soon as the test suite encounters a failure, we want the execution to stop. This ensures that the person implementing the solution sees only one error or failure message at a time, unless they make a change which causes prior tests to fail.

This is the same experience that they would get if they were implementing each new test themselves.

Most testing frameworks do not have the necessary configuration options to get this behavior directly, but they often do have a way of marking tests as _skipped_ or _pending_. The mechanism for this will vary from language to language and from test framework to test framework.

Whatever the mechanism—functions, methods, annotations, directives, commenting out tests, or some other approach—these are changes made directly to the test file. The person solving the exercise will need to edit the test file in order to "activate" each subsequent test.

Any tests that are marked as skipped will not be verified by the track test suite unless special care is taken.

Additionally, in some programming languages, the name of the file containing the solution is hard-coded in the test suite, and the example solution is not named in the way that we expect people to name their files.

We will need to temporarily (and programmatically) edit the exercise test suites to ensure that all of their tests are active. We may also need to rename the example solution file(s) in order for the exercise test suite to run against it.

**Avoiding accidental git check-ins**

It's important that if we rewrite files in any way during a test run, that these changes do not accidentally get checked in to the git repository.

Therefore, many language tracks write the track test suite in such a way that it _copies_ the exercise to a temporary location outside of the git repository before editing or rewriting the exercise files during a test run.

**Working around long-running track test suites**

Usually as people are developing the track, they're focused on a single exercise. If running the entire track test suite against all of the exercises takes a long time, it is often worth making it possible to verify just one exercise at a time.

**Example build file**

The PHP track has created a [Makefile][make]. The Ruby track uses Rake, which is a tool written in Ruby, allowing the track maintainers to write custom code in the language of the track to customize the build with a [Rakefile][rake].

[make]: https://github.com/exercism/xphp/blob/master/Makefile
[rake]: https://github.com/exercism/xruby/blob/master/Rakefile

**Comment by bencoman** [comment]
Pharo provides Jenkins CI to the community at (https://ci.inria.fr/pharo-contribution).

A second alternative facilitates Travis CI using (https://github.com/hpi-swa/smalltalkCI).
This is used by the OpenSmalltalk-VM (https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/.travis.yml)

Is there a generic testing api-key that can be used against the Exercism services?

**Comment by macta** [comment]
I'm not sure if we actually have the need to use Smalltalk-CI (it possibly does a lot more than we actually need - as it handles builds for multiple architecture types and OS's) we could launch pharo headless and run the tests (we have examples of doing this kicking around).

**Comment by macta** [comment]
This one is on my radar as we had a Recent merge that silently caused a load failure for dev’s.

It’s early days of course - but we can easily do something.

**Comment by macta** [comment]
This was noted on the Slack channel that a number of tracks (including Pharo ) don’t do CI test checks. Needs to get some love now we have something working

**Comment by bencoman** [comment]
Reading this...
> However, in order to simulate TDD we want tests to run _in the order that they are defined_, and we want them to _fail fast_, that is to say, as soon as the test suite encounters a failure, we want the execution to stop.

One approach would be a downloaded exercise having test methods named:
```
ExceriseTest>>01testSomething
ExerciseTest>>02testSomethingElse
ExerciseTest>>03testAnotherThing
```
and we can provide menu options `Exercism enable test` that doe sthe refactoring to rename `01testSomething` to `testSomething`. 

And this...
> It's important that if we rewrite files in any way during a test run, that these changes do not accidentally get checked in to the git repository. Therefore, many language tracks write the track test suite in such a way that it **copies** the exercise to a temporary location outside of the git repository before editing or rewriting the exercise files during a test run.

Our CI testing could copy class `ExceriseTest` to `ExerciseTestCopy` before running the CI on that after bulk renaming its methods to enable them.

**Comment by macta** [comment]
We now have SmalltalkCI running and testing our examples. I still have some issues running our Tools tests (https://github.com/hpi-swa/smalltalkCI/issues/417) so those are excluded for the moment.

We don't rewrite any example files - our just generate copies and check those into the examples tree.

With regards to running in a known order - as its easy to click on a single test and run it, I worry less about the run-all function in the ide. It does raise the question of whether we should order the tests in the ide (currently alphabetic). I will stick a seperate issue for this.

**Comment by kytrinyx** [comment]
This is exciting! Congrats :)

**Comment by macta** [comment]
I'm closing this one as I think we have what's needed in the spirit of the story
