### ISSUE TITLE
Move Exercise tags over to full Packages

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#302]
Our use of pharo tags (e.g. Exericism-HelloWorld) was a nice way to organise exercises in the image (so they can collapse and also provide a top level menu item) - however the direction of pharo is to keep tags a light weight categorisation and instead rely on a Project for organisation. 

The current tag usage has some issues we need to address:
1) Extension methods aren't supported in tags and the data is not available to do this
2) Useful tools like the Critique engine also work at the package level

The guidance from upstream pharo is to use Packages, and so we need to port the existing tags to top level packages.

Without projects, its still useful to see all the exercises together (and not mingle in the development/support packages), so we need a useful prefix (later a project might work fine, when that work is complete).

I propose experimenting with Exercism_<name>, which should put all our exercises above the support packages (alternatively we rename ExercismDev, ExercismTest etc to move them away for the exercises).

It shouldn't be much work to do this - the menu detection code will need adjustment, and having an Exercism entry in the new menu bar now addresses the issue with how to load a new exercise if you don't have any loaded. This should also clean up the problem with Welcome dirtying the image (we wouldn't have to move it).

**Comment by bencoman** [comment]
> so we need a useful prefix 
For quite a while I've quietly thought the 'Exercise-'
would be a good way to distinguish exercises from our "Exercism-" dev environment.

**Comment by macta** [comment]
I hadn’t spotted the subtlety of Exercise vs Exercism (but quite like it) ... the issue with the $- separator is it gets interpreted as a tag (unless programmatically applied, which is a pain).

I played with Exercism@ eg Exercism@HelloWorld, which wasn’t too bad, and gave an easy backwards compatibility with menu detection etc.

How do you feel about that? (But could explore ExerciseHelloWorld or Exercise_HelloWorld (or @ too)

**Comment by bencoman** [comment]
Part of this will rearranging what Iceberg perceives as full packages.  Iceberg seems to use disk-folder arrangement and the **packages.st** file to determine what are full packages. I have successfully rearranged this from the command-line - WIP PR incoming shortly for review.

The other part is that our Exercism "downloading" of exercises is independent of Iceberg's arrangement. 
 It only has the [text string of #category:](https://github.com/exercism/pharo-smalltalk/blob/master/dev/src/Exercism/Acronym.class.st#L7) to parse and depends on whether a top-level **Exercism** package exists when each exercise is loaded.  Without pre-creating that, the exercises naturally install as full-packages.  

To demonstrate, try this...
1. In a fresh image, open a System Browser, 
2. then open Iceberg and add exercism/pharo-smalltalk repo,
3. then in its packages window, right-click **ExercismTools** and *Load* it.
Notice that the **Exercism** package was also created.

4. In Playground, evaluate... 
`(ExercismDownloadCommand track: 'pharo' exercise: 'hello-world') execute`
Notice **HellowWorld** is located in a subtree under **Exercism** package.
5. Now delete the **Exercism** package, and again evaluate...
`(ExercismDownloadCommand track: 'pharo' exercise: 'hello-world') execute`
Notice **Exercism-HelloWorld** is now a top-level package.

**Comment by bencoman** [comment]
Branch **pullRequest2** has exercises refactored to individual packages.
@Macta could you take a look.

**Comment by macta** [comment]
Ha - we did the same change (sorry I was on a plane and so didn't see your commit - or skimmed your notes and missed the actual commit) - however I scripted it in Pharo (but it looks like it got the same result, which is encouraging). I did:

```
RPAckageTag>>promoteAsExercismRPackage
	"This method converts this rpackage tag into an rpackage compatible with exercism"
	|  tagName pkgName promotedName pkg |
	
	tagName := self name.
	pkgName := self packageName.
	promotedName := self categoryName.
	
	self promoteAsRPackage.
	
	pkg := RPackageOrganizer default packageNamed: promotedName.
	pkg renameTo: pkgName, '@', tagName

Playground:
ExercismManager exercismPackage classTags do: [ :t | t promoteAsExercismRPackage ].
```

Looking at my branch (which I figured I would commit), just to compare with what you did (as I hadn't grok'd the package.st bit) - I see that they are the same.

**Comment by macta** [comment]
As you say - there are still some, funnys with the Exercism package being created - i actually focused more on how to support both representations so people who update their image can load newer @ exercises and then convert older ones if they want to (new people will just get the @ stuff and be blissfully unaware). It looks pretty simple as when I extracted an Exercise class, I pipe everything through that, and so nicely encapsulated it (accidently, or subconsciously) - see senders of exercismPackage and exercismPackageTag which is where it leaks out.

**Comment by bencoman** [comment]
Cool. Run with yours.

**Comment by macta** [comment]
closing - but we don't have an easy way to communicate to existing users to use the upgrade instructions in: https://exercism.io/tracks/pharo-smalltalk/installation

If anyone complains about how to submit the new style format (e.g. missing submit menu), they will need to be directed on how to upgrade.
