### ISSUE TITLE
First test should direct students to read class comment

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#322]
Only after spending days working on FrameTests for the Bowling exercise did I notice that that BowlingTest has a really great class comment.  

It may be useful for the comment of the first test direct students to read the class comment... "Review the problem specification in the class [Comment] tab" ?

**Comment by macta** [comment]
The Welcome test does tell you to read class comments for all future tests... and pay attention to the hints.

**Comment by bencoman** [comment]
I saw that when I was testing a fresh "student" image, but its easy to miss. 
I think its good to provide this additional prompt.
