### ISSUE TITLE
mentor tool to parse string input Tonel 

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#323]
@macta I understand you are developing some mentor review tools.  I haven't yet tried to discover them, but already reviewing a few submissions.  So this may parallel existing feature or end up irrelevant, but just to share a thought... when reviewing submissions on the web site, it would be useful to copy-paste the Tonel submission into a text input box that parsed the Tonel and installed the solution in the image.

**Comment by macta** [comment]
This is already in the dev image - see Exercism | View Mentee solution ...

**Comment by macta** [comment]
Due to name space issues (as you probably want to see the reference solution at the same time ), it’s a ring2 model with a Calypso browser that lets you view defences etc.

**Comment by macta** [comment]
Probably could doc it better  - you can record comments on methods / classes and generate the review to paste into the web site
