### ISSUE TITLE
AtbashCipher >> splitInGroupsOfFive:

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#324]
For discussion before submitting a PR, I found the following...
```
AtbashCipher >> splitInGroupsOfFive: aString 
	aString size < 6
		ifTrue: [ ^ aString ].
	^ String streamContents: [ :stream |
		aString doWithIndex: [ :each :i |
			(i > 1 and: [ i - 1 isDivisibleBy: 5 ])
				ifTrue: [ stream << Character space ].
			stream << each ] ]
```
a bit convoluted to understand at a glance, compared to...
```
AtbashCipher >> splitInGroupsOfFive: stringToSplit
    |input output|
    input := ReadStream on: stringToSplit.
    output := WriteStream on: String new.
    output nextPutAll: (input next: 5).
    [ input atEnd ] whileFalse: [ 
        output space.
        output nextPutAll: (input next: 5) ].
    ^ output contents
```

(btw, Are there many other solutions that demo the use of streams?)

**Comment by macta** [comment]
Well they both have merits, the former doesn't repeat the next: X bit, but equally the next: X is a nice indicator of chunking... I'd approve either - and its a nice example of how you can solve things many ways.

I am liking the streamContents: convention lately though.

**Comment by bencoman** [comment]
> I am liking the #streamContents: 

my #whileFalse: could be wrapped by #streamContents:

> former doesn't repeat the next: X 

but you have special cases for `size < 6` and `i > 1` and `i - 1` divisible by five.
Borrowing your ''i > 1' condition I get...
```
splitInGroupsOfFive: stringToSplit
    |input|
    input := ReadStream on: stringToSplit.
    ^ String streamContents: [ :output |
        [ input atEnd ] whileFalse:  
            [   output position > 1 ifTrue: [output space].
                output << (input next: 5).
            ] 
    ]
```
but I prefer it without the condition. So I ended up with...
```
splitInGroupsOfFive: stringToSplit
    |input|
    input := ReadStream on: stringToSplit.
    ^ String streamContents: [ :output |
        output << (input next: 5).
        [ input atEnd ] whileFalse: [ output space << (input next: 5) ] 
    ].
```
