### ISSUE TITLE
Clock Exercise : RBIfTrueReturnsTrue rule on code made by the compiler

### ISSUE THREAD

**Issue by ghost** [exercism/pharo-smalltalk#341]
On the clock exercise , you can make the equality and hash code with the menu. 
it looks like this : 

```
= anObject
	"Answer whether the receiver and anObject represent the same object."

	self == anObject
		ifTrue: [ ^ true ].
	self class = anObject class
		ifFalse: [ ^ false ].
	^ minute = anObject minute and: [ hour = anObject hour ]
```

critiz do not like the code with this message : 

ifTrue/ifFalse: returns instead of and:or:

**Comment by macta** [comment]
This should be reported to Pharo - the rule should be updated

**Comment by RoelofWobben** [comment]
oke, who is making the issue then ?

**Comment by macta** [comment]
Your chance for glory - if you can write one on Pharo-project : give image version and os (but not os specific) and clear details (screenshot good too), explain its Exercism but not an Exercism specific issue.

Ref the issue in ours so we can track.

Now your paying back.

Tim
