### ISSUE TITLE
ResitorColorDuo (GRUndeclaredVariableRule) 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#342]
in the setup of this challenge is stated : 

setUp
	resistorColorDuoCalculator := ResistorColorDuo new

but according to critiz it's not there where I can see there is a object with that name.

**Comment by macta** [comment]
Looks similar to https://github.com/exercism/pharo-smalltalk/issues/344 - same experiment - does saving the method again fix it? If so - report to Pharo

**Comment by RoelofWobben** [comment]
This one is gone with making the list not making a inst variable.
