### ISSUE TITLE
Robot Simulator (GRUndefinedVariableRule) 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#344]
![afbeelding](https://user-images.githubusercontent.com/47429430/57719244-98eb6a80-767f-11e9-8286-614360b8bd13.png)

**Comment by macta** [comment]
Yeah that looks like the compiled method is cached in an incorrect state. If you save that method again (put a space at the end) does it go away? If so - should be reported to Pharo

**Comment by RoelofWobben** [comment]
also gone after a extra safe

**Comment by macta** [comment]
Actually we should log this on Pharo - it’s supposed to stay up to date.
