### ISSUE TITLE
Robot Simulator  (RBClassNotReferenced) 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#345]

**Comment by RoelofWobben** [comment]
![afbeelding](https://user-images.githubusercontent.com/47429430/57719367-e536aa80-767f-11e9-8151-d02faec25d22.png)

**Comment by macta** [comment]
Can you clarify this - is your class referenced - eg show the screen with References to one of the Red classes

**Comment by RoelofWobben** [comment]
hmm, I use DD so I have to think how to show the reference

**Comment by RoelofWobben** [comment]
Is there a way I can see if the classes are referened. Wierd that 50% of the classes I made are not referenced and the rest is

**Comment by RoelofWobben** [comment]
hmm, there are all subclasses of Instruction which I call here : 

process: aInstruction
	| instruction |
	instruction := Instruction subclasses
		detect: [ :class | class instruction = aInstruction ].
	^ instruction performOn: self

**Comment by RoelofWobben** [comment]
Wierd. I did a update and this one disappeared without chancing anything to the code. Im closing this one

**Comment by bencoman** [comment]
> Is there a way I can see if the classes are referened

Right-click on the class and choose "Class refs"
