### ISSUE TITLE
ExercismTests should ignore GRTemporaryNeitherReadNorWrittenRule

### ISSUE THREAD

**Issue by ghost** [exercism/pharo-smalltalk#348]
I see a lot of these on the test 

![afbeelding](https://user-images.githubusercontent.com/47429430/57770687-22974880-7711-11e9-9f65-3552ddaaec1d.png)

**Comment by bencoman** [comment]
I'm looking at TournamentTest>>test01 to test11 and not seeing any critiques.

**Comment by RoelofWobben** [comment]
sorry, I mean the Bowling one 
I will update the title

**Comment by bencoman** [comment]
Okay, I see it on Bowling  test15 to 18; 21 to 30.
All these tests are of the form...
```
test15_RollsCannotScoreNegativePoints
	| result |
	self
		should: [ result := bowlingCalculator scoreRolling:  -1 after: #() ]
		raise: Error
		whoseDescriptionIncludes: 'Negative roll is invalid'
		description: 'Should get an error with the correct description'
```

The critique is correct. The temporary variable is not read, just thrown away.
Can generator be improved?

**Comment by RoelofWobben** [comment]
no idea, I hope Tim can answer this

**Comment by macta** [comment]
Yes we could change the generator but I’m going to push back - for tests having variables assigned to values is useful in understanding the failure - or lack of failure. So I’d be tempted to exclude tests from that rule - although it’s trying to tell you that an unused variable might be sign that you expected something to happen - but in a test, I err on the side of lots of intermediate variables to see what is happening if I debug.

**Comment by RoelofWobben** [comment]
for me also a solution.

**Comment by Bajger** [comment]
No longer relevant. Code critique works just fine for tests on BowlingTest.
