### ISSUE TITLE
[TwelveDays] might use #joinUsing:last: 

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#386]
A student submitted the following and its the first I knew of #joinUsing:last:
That may make a better canonical solution.

```
TwelveDays >> getVerse: anInteger [
	| elements |
	elements := (self verses first: anInteger) reverse.
	^ 'On the ' , (self dayName: anInteger)
		, ' day of Christmas my true love gave to me: '
		, (elements joinUsing: ', ' last: ', and ') , '.'
```

**Comment by samWson** [comment]
I'm comparing this with `#giftsOnDay:` from the canonical solution:
```
giftsOnDay: anInteger
  ^ anInteger = 1
    ifTrue: [ self gifts first ]
    ifFalse: [
        | gifts |
			
            gifts := (self gifts copyFrom: 1 to: anInteger) reverse.
            (gifts allButLast inject: '' into: [ :str :each | str , each , ', ' ]) , 'and ', gifts last ]
```

What I like about the students solution is that returned string is close to a template. It's a bit easier to read and understand what is supposed to be returned.

I notice in the canonical solution the code critic is recommending streams over string concatenation inside iterations. I think this student solution would have the same problem. We could push for use of streams but it might make this solution less readable which is its advantage for me. At least in the case of this exercise we know the maximum number of iterations we will have.

**Comment by bencoman** [comment]
I've been meaning to disable that "streams over string concatenation" critic.  Its not an absolute rule and is the one most often questioned on the Pharo mail lists.  I think there is already an issue for it.

**Comment by macta** [comment]
Guys - there isn’t a “canonical “ solution per say - we just have to solve a problem to show we’ve thought about it and have a useful reference point for mentoring.

This said - updating “our solution” has been useful to help guide mentors (and I often look at them to remind me how I did it). I actually like the idea of having multiple “different” solutions in our reference baseline to reflect that there are many different ways to solve a problem (a few of our solutions have this, and I think we should do it a bit more - the trick is having a good way to run the same tests over each of them to keep them up to date).

**Comment by samWson** [comment]
I see that `FlattenArray` has more than one solution. Is it a good example of how to approach having more than one solution for an exercise? If so I'd like to have a go at adding it.

**Comment by macta** [comment]
Hmmm -for a moment I couldn’t find FlattenArray - but yes, that’s an example of how to do it (not the most elegant , but it does work and has the benefit that its simple to understand).

I think we should offer a few more like that so we can show several interesting alternatives when we find them (and we might be able to leverage this for the auto-mentor mode when we get to it)

Tim

**Comment by samWson** [comment]
I've merged the alternate solution. I think we can call this closed.
