### ISSUE TITLE
Fetch of "reverse-string" does not work

### ISSUE THREAD

**Issue by marchukov** [exercism/pharo-smalltalk#388]
I am unable to fetch "reverse-string" exercise in World -> Exercism -> Fetch New Exercise... with 

"Tonel Parse Error: Can't parse type." 

I tried other exercises and I can fetch them normally.

I am using: Pharo 7.0.3
Build information: Pharo-7.0.3+build.162.sha.814fd1b03d3d717fcd9032f374203c3047ca2870 (64 Bit)

**Comment by marchukov** [comment]
Attaching my Pharo Image with the error opened (though I have to reset my Exercism token, so it will not work as is) [Exercism.zip](https://github.com/exercism/pharo-smalltalk/files/3428386/Exercism.zip)

**Comment by macta** [comment]
Is it just this exercise that has the problem? Others are working fine? And is this the initial retrieve (eg you aren’t retrieving your solution - it’s the initial download?)

**Comment by marchukov** [comment]
@macta so far only "reverse-string" is having this problem for me. It is not the first retrieve. I also tried to fetch "space-age" and it works fine.

**Comment by marchukov** [comment]
I tried it on a clean Pharo 7.0 64 bit stable image with the current exercism code from github://exercism/pharo-smalltalk/releases/latest and I get exactly same error. And only for "reverse-string".

**Comment by macta** [comment]
@bencoman , you recently changed this exercise, might it have broken?

**Comment by bencoman** [comment]
Yes, looks like I dropped escaping of the comment character 
https://github.com/exercism/pharo-smalltalk/pull/387/files#diff-2f4a67964d6d2abbe65c09aae91fee50L25-R25

**Comment by bencoman** [comment]
I've uploaded a fix [1] but I'm not sure of the lag for that to flow through to make sure I got it right.
[1] https://github.com/exercism/pharo-smalltalk/pull/389/files#diff-4cd205159f42e26fe4aa4380cae911c3L25-R25

**Comment by marchukov** [comment]
Is it automatic from git or somebody have to push this to the Exercism itself?

**Comment by samWson** [comment]
@marchukov sorry nobody got back to you on this sooner. I don't know how or when the new code gets from GitHub to the Exercism website but at a guess I'd say it's ready to go. I just downloaded the exercise myself without any problems. Note that you may need to go to the exercise web page and update the exercise to the newer version if you have already managed to make a submission.

Let us know if you have anymore problems.
