### ISSUE TITLE
The exercise you are submitting doesn't have the necessary metadata, help pls

### ISSUE THREAD

**Issue by Sunny04073** [exercism/pharo-smalltalk#393]
Help pls, unable to submit, tried for 2 hours
C:\Users\Testing_Lab>exercism configure -w C:\Users\Testing_Lab\Exercism\python\hello-world\python\hello-world

You have configured the Exercism command-line client:

Config dir:                       C:\Users\Testing_Lab\AppData\Roaming\exercism
Token:         (-t, --token)      bd1daa8f-c71b-44b0-9f57-60b2bd1341d7
Workspace:     (-w, --workspace)  C:\Users\Testing_Lab\Exercism\python\hello-world\python\hello-world
API Base URL:  (-a, --api)        https://api.exercism.io/v1

C:\Users\Testing_Lab>exercism submit C:\Users\Testing_Lab\Exercism\python\hello-world\python\hello-world\hello_world.py
Error:

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.

**Comment by samWson** [comment]
Hi @Sunny04073. I'd guess that your exercism command-line client is an old version. The text you have at the bottom shows where to go for instructions to upgrade it.

> Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.

[The instructions are here](https://exercism.io/cli-v1-to-v2). There is a link to the latest release of the client and interactive instructions.

Also it looks like your configuring the client for the *Python* language track. This is the repository for the *Pharo-smalltalk* language track. 

If your still having problems after upgrading the command-line client and you want to work on the Python track then raise an issue on the [Python language track repository](https://github.com/exercism/python) and the maintainers there should be able to help. If you want to work on the Pharo-smalltalk language track then post your comments on this issue and we will help you if we can.

**Comment by macta** [comment]
If you like python, you should give Smalltalk a spin too... they are quite similar and hopefully you can take away some interesting ideas. You often find interesting approaches you can port to other languages. While Smalltalk predates Python, our community has borrowed quite a few neat python ideas over the years.

Anyway - good luck in your experiments.

**Comment by samWson** [comment]
I'm closing this issue. @Sunny04073 if you are still having problems and need help you can get in touch with us by commenting on this issue and we can re-open it.
