### ISSUE TITLE
Sieve: alternative solution

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#394]
A very nice solution was submitted by Exercism user "alyssap" that I find easier to understand than our current solution.  Perhaps we could adopt it...
```
Sieve >> primesLimit: anInteger [
  | primes numbers |
  primes := Stack new.
  numbers := Array new: anInteger.
  2 to: anInteger do: [ :i | 
    (numbers at: i) ifNil: [ 
       primes push: i.
       i to: anInteger by: i do: [ :j | numbers at: j put: #no ] ] ].
  ^ primes reversed
```

**Comment by bencoman** [comment]
Indeed, the problem statement says "It does not use any division or remainder operation" and our current solution does use division.  Here is a slightly modified version...
```
Sieve >> primesLimit: anInteger [
  primes := Stack new.
  marks := Array new: anInteger.
  marks at: 1 put: #notPrime.
  marks doWithIndex: [ :mark :number |
    mark ifNil: [ 
      primes push: number.
      number to: anInteger by: number do: [ :notPrime | 
        marks at: notPrime put: #notPrime ] ] ].
  primes reversed
```

**Comment by macta** [comment]
Where it makes sense, I’d suggest we have multiple solutions (keeping the best one of course).

I’m always impressed with the interesting solutions that keep popping up.

**Comment by samWson** [comment]
@RoelofWobben would you like to take on this issue? We started collecting alternative solutions like this one an add them to our exercises.

For an example of how we have done this before checkout the [flatten array exercise](https://github.com/exercism/pharo-smalltalk/tree/master/dev/src/Exercise%40FlattenArray). You will see the `FlattenArray2` and `FlattenArray2Test` classes. Those are the extra solution for that exercise.

**Comment by RoelofWobben** [comment]
Oke, 

I have the files. Do I need to generate them or can I just push my changes ?

**Comment by samWson** [comment]
@RoelofWobben I don't know if the file generator would create files from alternate solutions. The flatten array exercise still only has one solution and test. In any case we still only want to have one test and solution for the website so it should be fine to not run the file generator.

**Comment by macta** [comment]
Guys - the solutions are only to show that there is a solution, which unlocks the exercise - students never see them , which is why I’m always surprised at everyone being keen to add lots of alternatives... 

This said, useful alternate solutions are useful for mentors to refer to, who presumably have the dev image open with the mentor tools... so can see alternatives for reference.

For auto- marking (which we never got around to implementing), it may be possible to use these for comparing alternatives automatically.

Hope that helps.

Tim

**Comment by RoelofWobben** [comment]
We could also choose for only 1 solution which is the most idiomatic.
