### ISSUE TITLE
Fix code snippet in README

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#40]
There is something odd about how the code snippets are being rendered in the README. However looking at the markdown code it appears to be fine.

![badly-rendered-markdown](https://user-images.githubusercontent.com/13286932/43674333-64caf1d6-9826-11e8-91f4-7a8e483985f6.jpg)

When I have a look at the same file in MacDown on my computer, the code snippets are rendered and displayed correctly. Maybe there is some small quirk with how Github renders markdown?

**Comment by macta** [comment]
Yeah it's weird - the markdown is supposed to imply that the code and paragraphs are indented under the 2nd list item - but its not doing that. I think I might have to just forgo the numbered items?

**Comment by samWson** [comment]
Closing this. Not relevant anymore.
