### ISSUE TITLE
space-age will not submit

### ISSUE THREAD

**Issue by circius** [exercism/pharo-smalltalk#404]
Hello,

I'm unable to submit the exercise 'space-age' from pharo. clicking the 'submit' button in the exercism right-click menu results in the following error message:

`KeyNotFound: key 'AnObsoleteSpaceAge' not found in SystemDictionary`

it's not a big deal, but I thought you'd want to know. Everything else about the exercise seems fine.

**Comment by macta** [comment]
As the error is about “anObsoleteSpaceAge” was this an old image or one that was upgraded from an older version of exercism? I recall this being something we saw in older images.

**Comment by circius** [comment]
Oh, that's possible, I remember having some trouble with libgit2 and trying to route around that, but can't remember how I did I'm afraid. 

here's some information that seems like it might help diagnosing the situation. do let me know if there's something else I should dig up...

`➜ ./pharo-ui --version
5.0-201902062351  Wed Feb  6 23:55:13 UTC 2019 gcc 4.8 [Production Spur VM]
CoInterpreter VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Feb  6 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2509 uuid: 91e81f64-95de-4914-a960-8f842be3a194 Feb  6 2019
VM: 201902062351 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Date: Wed Feb 6 15:51:18 2019 CommitHash: a838346b
Plugins: 201902062351 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
Linux travis-job-a9dc83e9-9594-4e51-bcc9-7fbbb21425b4 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 i686 i686 i686 GNU/Linux
plugin path: ~/exercism/pharo-smalltalk/pharo-vm/lib/pharo/5.0-201902062351 [default: ~/exercism/pharo-smalltalk/pharo-vm/lib/pharo/5.0-201902062351/]
`

version information from Help -> About

`
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1134.sha.5173b0271894727189f261cb9eb9beaa3db3f205 (32 Bit)
`

**Comment by circius** [comment]
I came back to this, and was able to resolve it by using a 32-bit pharo 9 /devel image - in general the 32-bit images seem not to have the libgit2 problems - as the base image, and installing the exercism tools on top.

I suppose I had done something similar to give myself this problem in the first place - note that the image I was using was 32-bit - and perhaps I'll be giving myself more problems in the future, but for now I'll just career ahead.

thanks for your work on the exercism stuff, it's really joyful!

**Comment by samWson** [comment]
@circius Thanks for letting us know. Since the change in image seemed to make a difference could you tell us what image you were using when you got the first error e.g. was is a 64-bit pharo-9 devel image? That could be useful information for future reference if others run into the same problem later.

**Comment by circius** [comment]
The exercism pharo instructions for installing pharo [here](https://exercism.io/tracks/pharo-smalltalk/installation) have a link to a pharo image:
`curl https://get.pharo.org/64/ | bash`
this worked, of course, but then the installation of the exercism tools would fail because of problems with the library libgit2 which are quite widely [reported](https://github.com/pharo-project/pharo/issues/4463) (but this seems to be system specific, most people reporting are, like me, using recent editions of Fedora.)

so I just changed the 64 in the download link to '32' - which I suppose means I was using pharo 8.0.0 stable 32-bit? and then the installation worked, but down the track I ran into this problem.

**Comment by Bajger** [comment]
@circius Pharo track should work on P10 version now. If you encounter any problems, let us know. Otherwise issue can be closed.

**Comment by Bajger** [comment]
Closing issue, no longer relevant. Space-age tests are passing on P10.
