### ISSUE TITLE
discord invitation for pharo needs an update

### ISSUE THREAD

**Issue by nur-azhar** [exercism/pharo-smalltalk#405]
https://exercism.io/tracks/pharo-smalltalk/learning

https://discord.gg/QewZMZa

sorry i failed to figure out the file to send a pull request

**Comment by iHiD** [comment]
(cc @exercism/pharo-smalltalk )

**Comment by samWson** [comment]
I've updated the broken link. It should be pointing toward a functioning invitation now. Let me know if this is still an issue.
