### ISSUE TITLE
Exercism - problem with loading dependent classes within package/exercise

### ISSUE THREAD

**Issue by Bajger** [exercism/pharo-smalltalk#409]
Greetings exercists!
I'm having trouble loading previously sumbitted Exercism exercise, which is in one package.
![image](https://user-images.githubusercontent.com/45875448/79428657-c3981e80-7fc6-11ea-82a9-ba5286ce1dc9.png)

Issue here is that class definitions are stored within individual .st files and the load method do not resolve dependencies between classes. Is there a better way of load entire exercise package into the image, e.g. by loading entire package using TonelReader>>loadDefinitions method? 

Do you have idea, if TonelReader>>loadDefinitions resolves dependencies of same package implicitly? (I could probably test by myself :D)

If yes, then method for loading exercise could be changed to something like:
```
ExercismDownloadProgram>>installExerciseFor: submission

         (TonelReader on: submission sourcesDirectoryPath fileName: submission exerciseName ) loadDefinitions.
       		
	SystemAnnouncer uniqueInstance
		announce: (RPackageRegistered to: submission exercise exercisePackage).
	
```
But, I don't know if tonel reader expects already ordered .st files based on dependencies..hopefully not.

**Comment by samWson** [comment]
Hi @Bajger. Thanks for reporting this.

Can you tell me which exercise you were trying to load? I created a new image myself and loaded several exercises I had already completed to see if I would get the same error. I had no errors so I am still unsure myself about the root cause of the issue.

> Do you have idea, if TonelReader>>loadDefinitions resolves dependencies of same package implicitly?

I don't, but in `TonelReader` there is a method that might answer this:
```smalltalk
TonelReader>>loadDependencies
	"There should not be dependencies"
	dependencies := #()
```

I suggest changing the source code for `ExercismDownloadCommand>>installExerciseFor:` exactly like you have shown in that code snippet and then trying to load the same exercise again. Let me know how that goes.

**Comment by Bajger** [comment]
@samWson: Hi Sam! It happens to exercises that have multiple classes dependent on each other and order of loading is given alphabetically, I guess. You could check my exercises Tournament and Roman Numerals. I have there classes that have dependencies on classes that are loaded later on,  because they have name with alphabetical order next in line. E.g.:
````
Class {
	#name : #FiveToEightRomanNumeral,
	#superclass : #RomanNumeral,
	#category : #'Exercise@RomanNumerals'
}
```
is loaded first and then: 
```
Class {
	#name : #RomanNumeral,
	#superclass : #Object,
	#instVars : [
		'romanDigits',
		'digit'
	],
	#category : #'Exercise@RomanNumerals'
}
```
is loaded later on.

Anyway: I will test TonelReader capabilities. I see 2 options:
1) If TonelReader can resolve dependencies by loading entire package. Then rewrite of ExercismSubmission class is needed, that would store only source directory and package name, which is necessary for loading. References to individual files wouldn't be needed anymore.
2) If TonelReader cannot resolve dependencies, then we could add to collection variable class definitions that failed to load and repeat loading once again (recursivelly), until all dependencies are loaded. 
I will try to evaluate this.

**Comment by macta** [comment]
Guys - can I check if these exercises pre-date when we moved to a “package per exercise” change? Before that, we couldn’t support extension methods as we exported individual classes, but with that change we moved to a package to save it all in one go. I can’t recall if we tested dependent classes but I’m sure Roelof did - so curious if perhaps these are just old exercises in the old version format? If not - then perhaps we didn’t update the saving loading with a full package in mind.

**Comment by samWson** [comment]
Referencing merge request #311. Possibly the time when we moved to a "packager per exercise".

**Comment by RoelofWobben** [comment]
Was  that not how we did things before macta decided we could better do it this way ?  
When there is a branch ready  I can of course test things.

**Comment by macta** [comment]
I would say this issue is orthogonal to the move to an exercise per package , and probably better supported by it as per David’s observation.

I’m surprised we didn’t notice it before in testing, but I think it partially depends on the order of loading and equally only occurs in more complicated exercises .
