### ISSUE TITLE
Review "Publishing a Completed Exercise" section in README

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#410]
Step 2 states the following:

> Right click on the exercism Package and choose "Generate exercise meta data", this will generate exercise meta data in your seperate staging location

but it might be out of date. I just tried to follow this step and could see no "Generate" item on the menu. There is this method that seems to do the same functionality: `ExercismExerciseGenerator class>>generate`.

Let's make sure the documentation is up to date.

**Comment by timm-mwp** [comment]
I don't think this has changed - do you have the full development baseline loaded (its only in that baseline)

**Comment by samWson** [comment]
As far as I can tell I have the `dev` baseline. I loaded it up in the last few days.

Here is what happens when I right click on an exercise package:
![right-click-on-exercise](https://user-images.githubusercontent.com/13286932/86739474-029bb480-c08a-11ea-8e65-d399e33dc2f6.PNG)



In the World menu there is a generate option:
![world-menu](https://user-images.githubusercontent.com/13286932/86739560-147d5780-c08a-11ea-81d7-20b2359d281c.PNG)

**Comment by macta** [comment]
Sam - from memory, it might be in the top level system menu (not the context menu). There is an Exercism entry which also have reviewer tools in it as well.

**Comment by macta** [comment]
Apologies - I didn't look at your second picture - yes, its the "generate meta-data" option, which you then have to commit back (outside of pharo - as its not a true pharo source tree - and this is the slightly confusing bit - its an export of what you can run in pharo, without tests, and in a location that Exercism expects. This is why I think you could make this into a travis task to do this).

**Comment by samWson** [comment]
@macta thanks. It looks like just a quick rewording of the instructions is required. I'll get on to that.
