### ISSUE TITLE
exercism does not work in Pharo 9 

### ISSUE THREAD

**Issue by ghost** [exercism/pharo-smalltalk#414]
Hello, 

I can install exercism on Pharo 9 but as soon as I wanted to fetch a exercise I see this : 

![afbeelding](https://user-images.githubusercontent.com/59806635/87221744-adec8800-c36e-11ea-90e2-2162706d78f3.png)

**Comment by samWson** [comment]
Just a wild guess but the public interface for `WorldMorph` may have changed from v8 to v9. Hopefully there is another method that does what we want.

In any case this is low priority for the moment. v9 is the development version of Pharo. We know v7 works and our development instructions state to use with it. We can come back to this issue later.

Our [installation instructions](https://github.com/exercism/pharo-smalltalk/blob/master/docs/INSTALLATION.md#linuxosx-installation) on the exercism website will always download the latest non-development Pharo version (Linux/MacOS only). This is currently v8. As soon as v9 is made stable the script will download it instead and this problem will be more widespread.

**Comment by samWson** [comment]
We can revisit Pharo 9 support later when it becomes a stable release.
