### ISSUE TITLE
Where is stated that generate only do files which begin with exercise@

### ISSUE THREAD

**Issue by ghost** [exercism/pharo-smalltalk#415]
Hello, 

Im busy with porting exercises to the new v3 format and I think to take care that they do not get mixed up with the v2 exercises I like to use something like exercise3@name. 

But how do I tell the generator that I only wanted to generate exercises that begin with exercise3 instead of exercise ? 

Roelof

**Comment by samWson** [comment]
It probably can't do what you want. The language track never had the problem of different exercises across different versions of exercism. This will likely require a code change. I'll need to make myself familiar with that part of the code first.

**Comment by Bajger** [comment]
This is no longer relevant. All exercises should be "v3 compliant", in terms of source solution and test class. (except generating main config.json). I'd need to run lint, to check if all necessary metadata are there, when new exercise is  created from problem-specification or from scratch.
