### ISSUE TITLE
Build website artifacts with GitHub Actions

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#416]
The idea is that in solving this issue maintainers no longer have to manually generate all the files for the exercism website from the IDE manually. Instead an automated process does that as soon as new changes are merged. This issue will track that. I started an initial discussion on the [exercism](https://github.com/exercism/exercism/issues/5328) repo for some initial guidance.

**Comment by samWson** [comment]
Working on a theoretical action.

It runs when an event occurs. The event would be a `push` to branch `master`.

An action workflow has one or more jobs to run. In our case the jobs are the same that a maintainer would manually do to build new website files.

There are several steps to do. These could be in one job or many jobs.
- Check if any files that are used to generate website artifacts have been updated or new ones have been added
- Assuming the above is true inside an environment (e.g. Ubuntu Linux) download the latest supported Pharo image and VM
- Start the image
- Load the git repository
- Checkout master branch
- Load the relevant baseline from the repository
- Generate the website artifacts
- Commit the changed/new files to the repository
- Merge the commit to the website branch
- Push the repository changes back to origin i.e. this repository

At this point the exercism picks up the new files from our website branch and the exercises available to people are updated. Which branch is used might have to be configured elsewhere.

The separate website branch should never have to be manually edited by a maintainer during routine operations. It should be completely automated.

Actions are a new thing for me so there will be some learning for awhile before anything useful is made.

**Comment by samWson** [comment]
I have created a simple action in the `github-action` branch. Just a 'hello world' exercise that runs when a commit is pushed to the repository. It seems to work [fine](https://github.com/exercism/pharo-smalltalk/actions/runs/188273419).

Next step is for the action to do more complex things that match the desired workflow:
- run on push to a specific branch (`master` when this is in production)

GitHub actions are Yaml files stored in `.github/workflows/`.

**Comment by samWson** [comment]
I've created the branch `github-action-test`. It is just a target for the action to run when commits are pushed to the specific branch. I anticipate this being replaced with `master` in production.

**Comment by samWson** [comment]
I've updated the github action to checkout the repository and to `git show` to verify that it works. Moving forward I will do small incremental steps to verify what can be done and that things are working.

It looks like the action workflow file will need to be in master to test it out though. I have an updated file in branch `github action` but the version in `master` is being used instead.

**Comment by samWson** [comment]
#417 merges the latest workflow file into master. I'll make another test commit to see if the workflow runs as expected.

**Comment by samWson** [comment]
I just realized that branch `github-action-test` does not have the latest workflow file update because it was branched from master before the workflow file changed. Instead it is using an old version of the workflow file.

It might actual be possible to use a different version of a workflow file from the one in `master` it just needs to be on the same branch.

I'll try making changes to the workflow file in the same branch that I am pushing test commits to i.e. `github-action-test`. I'll also need to rebase the branch on master to get the latest version of the workflow file.

**Comment by samWson** [comment]
I've had some success. The workflow has checked out this repository and run `git show` to prove it has the latest commit on the `github-action-test` branch: https://github.com/exercism/pharo-smalltalk/runs/960766529?check_suite_focus=true

For the next step I want the action to download a Pharo image and VM and start it up from the command line. That will lead into loading the repository into the pharo image.

**Comment by samWson** [comment]
Some more success. The workflow can now download a Pharo image and VM and run a 'hello world' command. I'm using Pharo8 since it seems to be the latest version that can work with the repository.

There is an error in the VM. It can't upgrade its heart beat thread priority. It didn't stop the workflow from running but it could be an issue if the VM is under heavy load. Something to note for later. It's all in the workflow output.

https://github.com/exercism/pharo-smalltalk/runs/962869815?check_suite_focus=true

The next step is to get the image to load the repository.

**Comment by samWson** [comment]
I discovered that the [smalltalkCI](https://github.com/hpi-swa/smalltalkCI) project also makes a [Github action](https://github.com/marketplace/actions/setup-smalltalkci). This makes loading an image and VM into the action runner easy. It also takes advantage of the existing `smalltalk.ston` file we have to load the repository into the image and run all the tests.

What I'd like to do is see if smalltalkCI can run arbitrary smalltalk code instead of tests e.g. build all the web artifacts. Note that any change to the `smalltalk.ston` file will also be run in Travis which is possibly not what I want.

A build all artifacts step could be added as an after test action for smalltalkCI i.e. only build the artifacts if all tests pass.

This also raises the possibility of doing all of this work in Travis instead of a Github action.

[The latest workflow run.](https://github.com/exercism/pharo-smalltalk/runs/979497985?check_suite_focus=true)

**Comment by samWson** [comment]
It looks like smalltalkCI can run a smalltalk script other than the default `.smalltalk.ston`. Here are a couple of travis examples:
```yaml
# Override `script` to customize smalltalkCI invocation, e.g.:
script:
  - smalltalkci .mysmalltalk1.ston
  - travis_wait smalltalkci .mysmalltalk2.ston
```

```yaml
smalltalk_config:
  - .smalltalk.ston
  - .bleedingEdge.ston
```

I could have this whole testing & build process run in Travis. I want to avoid that for now because I don't know how easy it is for Travis to commit the build artifacts to the repository and push them back to Github. I'll leave the building to the Github action since it looks like git operations will be relatively easy. This means that I don't want smalltalkCI to use the `.smalltalk.ston` as that is the file that Travis uses so I'm going to try to make the action workflow use a different smalltalk script.

**Comment by samWson** [comment]
I've added `scripts/.build-web-artifacts.ston` which will run the tests and a post build step in `scripts/postTesting.st`. The action workflow is still only running `smalltalkCI -s Pharo64-8.0` and not passing `scripts/.build-web-artifacts.ston` as an argument. The problem could be the `${{ <file-name> }}` expansion in the workflow file.

**Comment by samWson** [comment]
I've discovered that `if` conditions are possible in action workflows. So I now have a clearer idea of all the parts I can use and how I want to use them.

The first step is to download smalltalkCI. It makes it easy to download smalltalk images and VMs.

The second step is to use smalltalkCI to download the Pharo image and vm. Then smalltalkCI will run the tests using the same `.smalltalk.ston` file that Travis uses.

The third step only runs if the second step succeeded. This is the build 'web artifacts step' and it will be an arbitrary command (just 'hello world' for now). smalltalkCI seems to work best with tests and set up and tear down scripts around tests, so I won't shoe horn it into doing something less related to testing.

At the moment the third step is failing because it can't find the `pharo` binary. This is the next problem to solve.

**Comment by RoelofWobben** [comment]
so , you are very busy with this thing. I hope you succeed very soon

**Comment by iHiD** [comment]
@samWson Nice work!

You might want to use the `pull-request` action not the `push` action so you can get it tested repeatedly without having to merge each time etc.

You might also like to bounce this with @ErikSchierboom or @saschamann who both know GHA pretty well :)

**Comment by SaschaMann** [comment]
> You might want to use the pull-request action not the push action so you can get it tested repeatedly without having to merge each time etc.
The push event is triggered whenever one pushes to a branch, it doesn't necessarily require merging.

**Comment by samWson** [comment]
I experimented with running smalltalkCI on my personal computer. I've figured out that smalltalkCI stores the image and VM it downloads in the `smalltalkCI/_builds` directory. One issue is that the image and VM are placed in another sub-directory named after a time stamp e.g. `2020_08_17_20_43_32`. This will make it difficult to run the VM from the action workflow because the directory path will be different every time.

I'll run a few experiments  and see what we can access from the shell in the action runner.

**Comment by ErikSchierboom** [comment]
> You might also like to bounce this with @ErikSchierboom or @SaschaMann who both know GHA pretty well :)

Yes, let me know if you need any help!

**Comment by samWson** [comment]
I had hoped for some guidance from the SmalltalkCI team but no one has responded to my issue. I don't think smalltalkCI has the flexibility to do what I want it to do. I'm returning to my original approach of detailing all the steps myself in the workflow.

I've had good success with the [latest changes](https://github.com/exercism/pharo-smalltalk/runs/1044629558?check_suite_focus=true). The workflow gets the repository and Pharo VM, puts them in appropriate directories, gets the configlet tool, and confirms that Pharo works with a 'Hello world' script.

The next step is to get the Pharo VM to build the website files. After that configlet runs the `lint` and `tree` commands like in our Travis file (`generate` is already run by the Pharo VM). After all that everything should be ready to make a pull request back to the repo on Github.

**Comment by fniephaus** [comment]
> What I'd like to do is see if smalltalkCI can run arbitrary smalltalk code instead of tests e.g. build all the web artifacts. Note that any change to the smalltalk.ston file will also be run in Travis which is possibly not what I want.

Well, you could easily run arbitrary Smalltalk code with smalltalkCI if it runs as part of a test. I have only skimmed the issue and I'm not sure what this project is about, but if you want to generate some artifacts from Smalltalk, why not add a test that does that? Only if all tests pass, deploy the output?

**Comment by samWson** [comment]
Hi @fniephaus. This project is the Pharo Smalltalk langauge track for [Exercism.io](https://exercism.io/). The files that I need the image to produce are for that website.

This issue is on hold for the moment. The Exercism team is working on the next version (v3) of its website and I'm focusing on getting the Pharo Smalltalk track ready for it.

Thanks for the advice. I'm sure I'll still have need for some automation in the future so I will give it a try.

**Comment by Bajger** [comment]
Closing this issue now, since Exercism Pharo Smalltalk build is already running via github actions, e.g.: https://github.com/exercism/pharo-smalltalk/actions/runs/3902764942/jobs/6666224512
- it downloads latest stable image (currently P10)
- installs dev baseline of Pharo smalltalk project
- runs all tests
