### ISSUE TITLE
Exercism | View Track Progress,  should open current exercise (and work on windows)

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#43]
Currently there is a beta option to open the current exercise (Which is done by shelling out to the os, and opening an exercism url).

This url is currently not linked to the exercise where you pick open (it needs a uuid)

We are currently exec'ing "open <url>", however open is osx specific whereas I think it's "run" for windows, and not sure for linux

**Comment by bencoman** [comment]
For Windows, "start" may be useful...
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start

**Comment by macta** [comment]
Ben also noticed the following package that will probably sort all of this out much more cleanly:
https://github.com/seandenigris/Pharo-Web-Browser

**Comment by macta** [comment]
We removed Pharo-Web-Browser as native open url support is provided in Pharo and that library brought in lots of extra pre-requisites.
