### ISSUE TITLE
Handle generator shell output better

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#44]
The exercism generator shells out to configlet to generate readme files but currently doesn’t handle the output particularly well, particularly if there is a failure (like not installed)

**Comment by macta** [comment]
I've tweaked it a little bit - but its still not very good. I suspect new students might get burned with this if things don't explain why they failed.

**Comment by samWson** [comment]
@macta is this issue fixed?

**Comment by macta** [comment]
Yes this is now fixed
