### ISSUE TITLE
[v3]  Wanted to join but see some problems 

### ISSUE THREAD

**Issue by ghost** [exercism/pharo-smalltalk#443]
Hello, 

I m be asked by the Pharo language team to investigate if and how Pharo can be a part of the new version. The biggest problem is that Pharo langauge is a image based language where the ide is a part of the language. So I think we need to discuss if and how to make this work with browser coding and if there is a way this can work 

@iHiD

**Comment by iHiD** [comment]
Hello. Thanks for wanting to contribute :) This conversation has happened quite a few times already. I believe that @samWson has a clear roadmap for how this is going to play out.

**Comment by iHiD** [comment]
Oooh, I think this is an old issue that GitHub is in a mess with because the original poster has been deleted.
