### ISSUE TITLE
Ensure Pharo track is ready for v2 launch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pharo-smalltalk#5]
There are a number of things we're going to want to check before the v2 site goes live. There are notes below that flesh out all the checklist items.

- [x] The track has a page on the v2 site: https://v2.exercism.io/tracks/pharo
- [x] The track page has a short description under the name (not starting with `TODO`)
- [x] The "About" section is a friendly, colloquial, compelling introduction
- [x] The "About" section follows the formatting guidelines
- [x] The code example gives a good taste of the language and fits within the boundaries of the background image
- [x] There are exercises marked as `core`
- [x] Exercises have rough estimates of difficulty
- [x] Exercises have topics associated with them
- [x] The first exercise is `auto_approve: true`

## Track landing page

The v2 site has a landing page for each track, which should make people want to join it. If the track page is missing, ping `@kytrinyx` to get it added.

### Blurb
If the header of the page starts with `TODO`, then submit a pull request to https://github.com/exercism/pharo/blob/master/config.json with a `blurb` key.  Remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### About section
If the "About" section feels a bit dry, then submit a pull request to https://github.com/exercism/pharo/blob/master/docs/ABOUT.md with suggested tweaks.

#### Formatting guidelines
In order to work well with the design of the new site, we're restricting the formatting of the `ABOUT.md`. It can use:

* Bold
* Italics
* Links
* Bullet lists
* Number lists

Additionally:

* Each sentence should be on its own line
* Paragraphs should be separated by an empty line
* Explicit `<br/>` can be used to split a paragraph into lines without spacing between them, however this is discouraged.

### Code example
If the code example is too short or too wide or too long or too uninteresting, submit a pull request to https://github.com/exercism/ocaml/blob/master/docs/SNIPPET.txt with a suggested replacement.

## Exercise metadata
Where the v1 site has a long, linear list of exercises, the v2 site has organized exercises into a small set of required exercises ("core").

If you update the track config, remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### Topic and difficulty
Core exercises unlock optional additional exercises, which can be filtered by topic an difficulty, however that will only work if we add topics and difficulties to the exercises in the track config, which is in https://github.com/exercism/pharo/blob/master/config.json

### Auto-approval
We've currently made any hello-world exercises auto-approved in the backend of v2. This means that you don't need mentor approval in order to move forward when you've completed that exercise.

Not all tracks have a hello-world, and some tracks might want to auto approve other (or additional) exercises.

## Track mentors
There are no bullet points for this one :)

As we move towards the launch of the new version of Exercism we are going to be ramping up on actively recruiting people to help provide feedback. Our goal is to get to 100%: everyone who submits a solution and wants feedback should get feedback. Good feedback.

If you're interested in helping mentor the track, check out http://mentoring.exercism.io/

#
When all of the boxes are ticked off, please close the issue.

Tracking progress in https://github.com/exercism/meta/issues/104

**Comment by samWson** [comment]
@kytrinyx I take it that the work I'm doing for getting this language track up and running on the original Exercism will be used in Exercism v2? Just wondering how much time I should dedicate to this issue and getting the language track started on the original website.

**Comment by kytrinyx** [comment]
@samWson Yes, I don't think you'll have to deal with v1 at all (we're a few weeks away from launching v2).

I've seeded the Pharo track here: https://v2.exercism.io/tracks/pharo -- we have webhooks that are watching the master branch for changes and updating the site... but discovered a bug in that. We have a PR open with a fix, so hopefully those updates will start happening automatically in the next couple of days (we're working across three timezones covering the UK, US, and the Philippines, so iterations and code review take a bit of time).

**Comment by macta** [comment]
@kytrinyx I'm trying to help Sam get something running - how can I commit changes to the repo? Do I need to fork and submit a PR or can I be added as a commiter. I'm not sure how all the pieces hang together - and ideally I'd like to commit a HelloWorld example to the exercises directory and update the readme etc (BTW does it have to be hello-world with a hyphen or can it be camel case which is more in keeping with Smalltalk anyway)

**Comment by bencoman** [comment]
@macta Section [naming conventions](https://github.com/exercism/docs/blob/4cd81c4c21a78ea193c1e7ccb48ce15d38909bf8/language-tracks/launch/decisions.md) seems relevant

**Comment by samWson** [comment]
@macta Looking at the Rust language track it appears to be one big repo, exercises and everything else. Each exercise has their own `.gitignore`. Looks like the approach is to clone the entire Pharo repo, add your code to the specific exercise directory then push a merge request when ready. I'd give you more permissions on this repo but I don't seem to have that power.

**Comment by bencoman** [comment]
@kytrinyx, what rough schedule do you have for v2 launch?  I think exercise-contributors should be developing the exercises in Pharo 7 since its git and Tonel support is better. In Pharo 6 these were technology previews.  It really won't matter for the exercises, but possibly for the the tool we make for students to push/pull exercises/solutions.

In our small community its easier to get community support for the active development HEAD (which is Pharo 7) than a released version.  Also we may even be able to get a link to Exercism into the help system for Pharo 7.  From what I gather from the mail list, Pharo 7 probably a Q4 release, with one of the main things getting 64-bit support for Windows (to catch up to 64-bit Linux/Mac supported in Pharo 6)

**Comment by kytrinyx** [comment]
@bencoman I'm catching up on about 6 weeks worth of notifications, I'm so sorry I didn't see this until now.

> does it have to be hello-world with a hyphen or can it be camel case which is more in keeping with Smalltalk anyway

@macta You can name the files themselves however you like, but exercise directory itself must be `hello-world` with a hyphen. This is used across the entire ecosystem in a number of different ways, and a lot of things will break if we aren't consistent with it.

>  can I be added as a commiter

Yeah, sorry--I see that we sorted that out in a separate discussion.

> I think exercise-contributors should be developing the exercises in Pharo 7 since its git and Tonel support is better.

@bencoman Yes, whatever you think makes sense for the track is fine here. The new Exercism is launched, but we don't have any deadlines for individual tracks. When you're ready, we can flip the switch.

**Comment by macta** [comment]
We are live so closing
