### ISSUE TITLE
add Classes to stub files

### ISSUE THREAD

**Issue by gypsydave5** [exercism/pharo-smalltalk#500]
Given https://github.com/exercism/pharo-smalltalk/pull/478 added stubs solution files to all of the exercises, which then breaks the fetching of exercises in Pharo (see https://github.com/exercism/pharo-smalltalk/issues/499), and also given the discussion on #478, we need to put classes inside these stubs.

Just opening this issue to give a place to start attacking and discussing the problem.

---

As we'll have to do this for all of the current exercises, and all future exercises, it seems like it would make the most sense if it was (at least eventually) automated.

I'm going to propose a script that could generate the right class based on the test files. Not sure if this would be more easily done in Pharo or something else.

**Comment by gypsydave5** [comment]
I'm not too familiar with exercism development _or_ Pharo, but is the only way of doing this editing each of the stub files outside of Pharo?

**Comment by RoelofWobben** [comment]
I also not , I see that the files are in the exercises directory but do not know how we can change them.

And I thought about it,  when we want to add the stub files , we have a lot of work to do for the current and for the challenges we added  just because some one decided that tracks needs to have a stub file. 

Is it then not fair that the person who made the problems, also solve them.
is now a lot of work for them but in the future not.

and for the test-runner, that is needed if we want to use the online ide , which I think never will happen for pharo because we cannot give them then the full pharo experience (TDD) , let the debugger make classes and methods and so on 

my 2 cts now I have thought about it

**Comment by gypsydave5** [comment]
>Is it then not fair that the person who made the problems, also solve them. is now a lot of work for them but in the future not.

I think that ship has sailed, nobody was keeping up with the changes for v3 of Exercism, or feeding back that this might be an issue. We are, as they say, where we are.

Reading https://github.com/exercism/pharo-smalltalk/pull/478#issuecomment-916690783 more carefully, I thing I prefer @Bajger's (b) idea of getting Pharo to just ignore the stub file on import. I agree with @RoelofWobben that at least having the option of generating the classes from the debugger when running the tests would be more idiomatic to Pharo development (or at least to how I've been doing it the last two months - what do I know?!)

**Comment by RoelofWobben** [comment]
@bajgers  have give me some code to ingnore the stub files when there are empty but that gave some more problems further in the chain.  so maybe he knows a way to get around that

**Comment by Bajger** [comment]
@gypsydave5 Well, to ignore a empty file did chain of other problems (as Roelof reported). I think creating stub files with empty class definitions isn't so much complicated. We can generate them programatically, then export them to .st files that will be put to dedicated directory of local repo (clone of dev baseline).

**Comment by gypsydave5** [comment]
I've made a commit to my fork that looks like it works by ignoring any empty (nil content) file:

https://github.com/gypsydave5/pharo-smalltalk/commit/80bccdd31a9f9f6fa7d92ee72b015e2001db8126

I've tested it manually by fetching and submitting `grains` - all OK.

The unit tests have one failure, but I believe it to be unrelated.

**Comment by Bajger** [comment]
Following code should give class .st files. I still can try to ignore empty file: 
```
#('Exercise@Acronym' 'Exercise@Allergies' 'Exercise@Anagram' 'Exercise@ArmstrongNumbers' 'Exercise@AtbashCipher' 'Exercise@Binary' 'Exercise@Bowling' 'Exercise@Clock' 'Exercise@CollatzConjecture' 'Exercise@Darts' 'Exercise@Diamond' 'Exercise@Die' 'Exercise@Etl' 'Exercise@FlattenArray' 'Exercise@Forth' 'Exercise@GradeSchool' 'Exercise@Grains' 'Exercise@Hamming' 'Exercise@HelloWorld' 'Exercise@HighScores' 'Exercise@IsbnVerifier' 'Exercise@Isogram' 'Exercise@Leap' 'Exercise@Luhn' 'Exercise@MatchingBrackets' 'Exercise@Matrix' 'Exercise@Minesweeper' 'Exercise@Pangram' 'Exercise@Proverb' 'Exercise@Raindrops' 'Exercise@ResistorColorDuo' 'Exercise@ReverseString' 'Exercise@RobotSimulator' 'Exercise@RomanNumerals' 'Exercise@SecretHandshake' 'Exercise@Sieve' 'Exercise@SpaceAge' 'Exercise@SumOfMultiples' 'Exercise@Tournament' 'Exercise@TwelveDays' 'Exercise@TwoFer' 'Exercise@Welcome' 'Exercise@WordCount') do: [:packageName | 
	|className execlass|
	className := (packageName splitOn: $@) last asSymbol.
	execlass := Object subclass: className
	instanceVariableNames: ''
	classVariableNames: ''
	package: packageName.
	execlass fileOut.
]

```

**Comment by gypsydave5** [comment]
> chain of other problems

What were they? I'd be interested as I've not hit anything (other than the weird coupling of data in the `ExercismSubmission` but that didn't take too much to fix).

**Comment by gypsydave5** [comment]
> Following code should give class .st files. I still can try to ignore empty file:
> 
> ```
> #('Exercise@Acronym' 'Exercise@Allergies' 'Exercise@Anagram' 'Exercise@ArmstrongNumbers' 'Exercise@AtbashCipher' 'Exercise@Binary' 'Exercise@Bowling' 'Exercise@Clock' 'Exercise@CollatzConjecture' 'Exercise@Darts' 'Exercise@Diamond' 'Exercise@Die' 'Exercise@Etl' 'Exercise@FlattenArray' 'Exercise@Forth' 'Exercise@GradeSchool' 'Exercise@Grains' 'Exercise@Hamming' 'Exercise@HelloWorld' 'Exercise@HighScores' 'Exercise@IsbnVerifier' 'Exercise@Isogram' 'Exercise@Leap' 'Exercise@Luhn' 'Exercise@MatchingBrackets' 'Exercise@Matrix' 'Exercise@Minesweeper' 'Exercise@Pangram' 'Exercise@Proverb' 'Exercise@Raindrops' 'Exercise@ResistorColorDuo' 'Exercise@ReverseString' 'Exercise@RobotSimulator' 'Exercise@RomanNumerals' 'Exercise@SecretHandshake' 'Exercise@Sieve' 'Exercise@SpaceAge' 'Exercise@SumOfMultiples' 'Exercise@Tournament' 'Exercise@TwelveDays' 'Exercise@TwoFer' 'Exercise@Welcome' 'Exercise@WordCount') do: [:packageName | 
> 	|className execlass|
> 	className := (packageName splitOn: $@) last asSymbol.
> 	execlass := Object subclass: className
> 	instanceVariableNames: ''
> 	classVariableNames: ''
> 	package: packageName.
> 	execlass fileOut.
> ]
> ```

wow this is cool - going to have to give it a few more reads to understand it.
