### ISSUE TITLE
Fix developer environment for P9

### ISSUE THREAD

**Issue by gypsydave5** [exercism/pharo-smalltalk#504]
Developer environment currently fails to be set up in Pharo90. Fails with `Error: Name not found: traitsSupport`. See below:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5469544/132967065-73bb6375-2176-4c96-be92-9376819e191a.png">

**Comment by gypsydave5** [comment]
Looks like it's the dependencies

First error we get to is from Ring2 - this project is now included in Pharo since Pharo80. So don't need that!

Next up is from the `OSProcess` dependency (http://www.squeaksource.com/OSProcess), which seems to exist to give a consistent interface to an OSProcess, and is necessary (to quote the `baseline:` method that installs the deps) `'OSProcess' "For shelling out to configlet"` - this happens during some of the generation commands that have been written to manipulate the repo file, e.g. `ExercismGenerate`. Think this is limited to the `ExercismDev` package.

I'm going to try ripping both of these dependencies out on a branch on my fork and seeing what happens...

**Comment by gypsydave5** [comment]
Right, we're getting somewhere:

https://github.com/gypsydave5/pharo-smalltalk/tree/504-Fix-developer-environment-for-P9

The only thing missing (I think) is a dropin replacement for `OSProcess`. Need some experienced hands to tell me what the right thing to update to is.

**Comment by gypsydave5** [comment]
OK I think we're going to need https://github.com/pharo-contributions/OSSubprocess

**Comment by Bajger** [comment]
I made some progress regarding changes in baseline: you can check on: 
```
Iceberg remoteTypeSelector: #httpsUrl.
Metacello new
 baseline: 'Exercism';
 repository: 'github://bajger/pharo-smalltalk:fix-pharo9-dev-baseline/releases/latest';
 load: 'dev'.
```
There is still some problem with OSProcess package, but I will work on it.
Warning message:
```
This package depends on the following classes:
  PipeableOSProcess
You must resolve these dependencies before you will be able to load these definitions: 
  FailedTestOSProcess
  FailedTestOSProcess>>#succeeded
  FailedTestOSProcess>>#waitForCommand:
  SuccessfulTestOSProcess
  SuccessfulTestOSProcess>>#succeeded
  SuccessfulTestOSProcess>>#waitForCommand:

```

**Comment by Bajger** [comment]
Aaah, I totally missed your contribution on your branch, so maybe you can compare `baseline:` from my branch with yours. I guess changes can be merged together. I think only difference I didn't remove Ring2 and ExercismToolsV70 packages from baseline completely, but just added Pharo version specific.

**Comment by gypsydave5** [comment]
@Bajger  - sorry, missed a lot of this. Sure, I think we should just merge them both together. I'll take a look tomorrow hopefully. Be good to keep the P7 stuff if at all possible. You happy to go with `OSSubprocess`?

**Comment by gypsydave5** [comment]
> @Bajger - sorry, missed a lot of this. Sure, I think we should just merge them both together. I'll take a look tomorrow hopefully. Be good to keep the P7 stuff if at all possible. You happy to go with `OSSubprocess`?

I still have no fix for the debugger thing. Really annoying, and I feel it's pretty important.

**Comment by Bajger** [comment]
I will try out few experiments with LibC (no skill at all), but I noticed a [discussion](https://discord.com/channels/223421264751099906/223421264751099906/887778056079540225) on general channel on discord asking about same thing. But I don't know if Configlet generator is bound to specific OS (Linux) or can be run also on Windows.

**Comment by gypsydave5** [comment]
Think it's cross platform - it's written in Nix(?) I think... Good to experiment with LibC!

**Comment by Bajger** [comment]
@gypsydave5: I was able to fix P9 'dev' baseline and adopted for us OSSubprocess and OSWinSubprocess libs (instead of OSProcess). Generator should use these OSSubprocess instrances now. It woks but broke P7 compatibility. I'm not sure if it is worth fixing it :) (P7 works with original code of OSProcess). I will add few more tests for newly defined methods (refactored of original code)
```
Metacello new
 baseline: 'Exercism';
 repository: 'github://bajger/pharo-smalltalk:fix-pharo9-dev-baseline/releases/latest';
 load: 'dev'
```

**Comment by Bajger** [comment]
So currently, in P7 my code works for default (user) baseline, but not mentor or dev baseline. I guess it can be left in that way (that dev/mendor packages works in P9 only), what do you think?

**Comment by gypsydave5** [comment]
I'm happy with this @Bajger; really don't think we should be sweating the P7 stuff for any of the use cases, but if it's working then that's great. I'd get this stuff merged in tbh and not wait for the Class generation fix.

**Comment by Bajger** [comment]
@gypsydave5: I will add few more tests for methods that aren't covered properly and issue a PR. And probably include changes in .md file with installation instructions for users.
