### ISSUE TITLE
Tests in isogram cannot work when the method is made a extension method.

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#512]
Hello, 

I made my solution of isogram a extension method of String 
but now the tests like this cannot find the method anymore.

```
test01_CheckIfTheGivenStringIsAnIsogramEmptyString

	| result |
	result := isogramCalculator isIsogramPhrase: ''.
	self assert: result equals: true
```

my solution : 

![afbeelding](https://user-images.githubusercontent.com/89863657/134559316-e9e429f5-6b19-45cd-88c9-a312f4297251.png)

**Comment by Bajger** [comment]
@RoelofWobben : it has simple solution, just call on Isogram class proper string method, something like: 
```
Isogram>>isIsogramPhrase: aString
     ^ aString isIsogramPhrase
```

**Comment by RoelofWobben** [comment]
it works  but not with the tests we have now.
So we have to make a choice let is as it is and  tell the users to ignore the suggestion to make things a extensions method 
Or change the tests but then a user must know how extensions methods work in P9.

**Comment by Bajger** [comment]
If it works, so hows your Isogram>>isIsogramPhrase: method look like?

**Comment by RoelofWobben** [comment]
Right now im doing this : 

```
isIsogramPhrase: aString

	^ aString isIsogramPhrase
	```  

to make the tests happy

**Comment by Bajger** [comment]
- Well, problem is that you send a message to String instance that is not implemented. You've implemented String>>isIsogramPhrase: (with a parameter), but you're sending in Isogram class method a message without a parameter...

**Comment by RoelofWobben** [comment]
no no, that one is also implemented 

```
isIsogramPhrase

	| cleanedString |
	cleanedString := self
		                 select: #isAlphaNumeric
		                 thenCollect: #asLowercase.
	^ cleanedString size = cleanedString asSet size
```

but my point is  that if you implement this code without the code in the Isogramm class the tests will fail
But according to the critic this is the right place for the code.
So my question stands
Do we accept that  our code is not totally according to pharo standards or do we change the tests ?

**Comment by Bajger** [comment]
It has nothing to do with coding standards or so. Our Exercism convenience is to have entry solution class and adequate test class counterpart. Solution class serves as interface, inner implementation can call whatever is needed, even own string methods. I would close this issue, because we don't want to confuse our users with inconsistency across exercises. Hope my answer helps you.

**Comment by RoelofWobben** [comment]
oke, clear point
