### ISSUE TITLE
Exercism in Pharo 10 can not fetch exercises

### ISSUE THREAD

**Issue by kderichs** [exercism/pharo-smalltalk#521]
When I try to load exercise the debugger comes up with:
"Instance of Path class did not understand #delimeter"

In Class ExercismHttpClient selector solutionPathFor: aString
it reads:
`(aString first = Path delimeter`
it should read:
`(aString first = Path delimiter`

After that everything works.

Pharo 10.0.0
Build information: Pharo-10.0.0+build.409.sha.9c2d1d3a0fbe2937b568984e72a81eb234b0866f (64 Bit)

**Comment by Ducasse** [comment]
Can you paste the exact code that we can execute to produce the error?
Tx

**Comment by Ducasse** [comment]
In my P10 class

```
Path class >> delimiter
	"Internal path delimiter"

	^$/
```

**Comment by Ducasse** [comment]
I do not understand why we would lose this method.

**Comment by Bajger** [comment]
Exercism method sends deprecated message (delimeter), yes it shoud be fixed to delimiter.
