### ISSUE TITLE
Fetching the same exercise doesn't work well

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#55]
The new exercism cli seems to create a suffixed new directory (e.g. -2) when you download an exercise again.

In Pharo this is invisible (your in the pharo ide).

We possibly shouldn't let you download again - or down shell out to exercism and just reload the source (which should essentially let you start again).

This needs a bit of a think

**Comment by bencoman** [comment]
We don't have separate namespaces, so the question is whether we:
1. Blindly overwrite existing 
2. Block action
3. Ask the student
Now we can download direct into Pharo, we can do (3.)

**Comment by macta** [comment]
The new http solution fixes this as it downloads the last solution you submitted (no cli suffixes now)
