### ISSUE TITLE
I Can Read C++ and Java But I Can’t Read Smalltalk

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pharo-smalltalk#83]
_Imported from https://github.com/exercism/docs/issues/120._
_Originally posted by @bencoman._

#

Should we reference or intermix parts of this document (which I love) ?
[readingSmalltalk.pdf](https://github.com/exercism/docs/files/2276414/readingSmalltalk.pdf)

**Comment by samWson** [comment]
@bencoman Great work. I've been reading the article myself in small bits at time. I think it will be useful.

**Comment by Bajger** [comment]
Article included already in learning resources: https://github.com/exercism/pharo-smalltalk/blob/main/docs/LEARNING.md#starting-out
Issue can be closed.

**Comment by glennj** [comment]
I get nostalgic seeing the name Wilf Lalonde. He taught me Smalltalk at Carleton U almost 30 years ago.

**Comment by Bajger** [comment]
> I get nostalgic seeing the name Wilf Lalonde. He taught me Smalltalk at Carleton U almost 30 years ago.

Lucky you! I remember document from Mr. Lalonde was one of our reference materials, when I studied Smalltalk class back in 2003 😄 
Our study course materials: http://perchta.fit.vutbr.cz:8000/smalltalk
refer to same document: http://www.eli.sdsu.edu/courses/spring02/cs635/readingSmalltalk.pdf
