### ISSUE TITLE
Create an Exercise Test generator

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#86]
I noticed that it can be a bit repetitive translating the problem specifications into tests - as they are in Json - its pretty trivial to generate the test class and methods for you based on the spec.

I think its better to generate actual methods as it makes it much easier to debug in the environment if you have a real method to restart (vs. dynamically doing asserts?)

This does hightlight some inconsistencies in the test specs - with regards to method naming, so manually tweaking it after generation is probably still handy.

**Comment by bencoman** [comment]
>
> I think its better to generate actual methods as it makes it much easier
> to debug in the environment if you have a real method to restart (vs.
> dynamically doing asserts?
>
Good idea.

**Comment by bencoman** [comment]
(I was in the Slack chat asking about loading track data into an empty local dev copy of the Exercism websit I got running on my laptop) And I saw some related comments...
> xarxziux 
I've done some work on a Node script to automatically convert problem specifications to test scripts for R. I started with the Acronym exercise and was able to successfully replicate the existing test through the automation script, but when I looked to convert other specifications, the format was quite different, if not inconsistent. Is anyone aware of any other automation tools out there that do something similar.

> Guy Gastineau
Ruby has a very well developed generator framework in place.
I developed a fairly barebones generator for Bash check it out at github - guygastineau/bash-track-test-generator.

>Brad Wood
If you like, you can also look at how I did it for the CFML Track.  We generate all of our test suites directly from the problem specifications using a CFML-based CLI Task Runner.
https://github.com/exercism/cfml/blob/master/tasks/GenerateTests.cfc
And you can see an example test suite that was generated:
https://github.com/exercism/cfml/blob/master/exercises/bob/BobTest.cfc (edited)

**Comment by bencoman** [comment]
@macta @samWson, Anyone worked on this?  Any general ideas?

**Comment by macta** [comment]
Hi - I had a poke, but it was too difficult on my travels to really run with it - so I’ve just toyed with it. The json is in a regular format and most  bits are named in a way to generate tests with simple assertions (where they aren’t - they should be and pr’s need to be submitted against exercism).

It’s really just a loop through all of them, generate test case, inner loop on assertions and generate tests.

Once generated, we need a way to ignore them  until we have solutions as the exercism linter will complain.

Tim

**Comment by bencoman** [comment]
Can you link some info on the Exercism linter?

**Comment by macta** [comment]
This is now in PR #144
